Repository NethermindEth/nethermind, pull requests merged in 2022-09, with the labels that each got.

#4450 ChainSpecEmbeddedResource
  scripts/deployment/build-runner.sh
  scripts/packaging/build-runner.sh
  src/Nethermind/Nethermind.Api/IInitConfig.cs
  src/Nethermind/Nethermind.Api/InitConfig.cs
  src/Nethermind/Nethermind.Config/Nethermind.Config.csproj
  src/Nethermind/Nethermind.Runner.Test/ChainspecFilesTests.cs
  src/Nethermind/Nethermind.Runner.Test/EthereumRunnerTests.cs
  src/Nethermind/Nethermind.Runner.Test/Nethermind.Runner.Test.csproj
  src/Nethermind/Nethermind.Runner.Test/goerli.json
  src/Nethermind/Nethermind.Runner/Ethereum/Api/ApiBuilder.cs
  src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoaderExtensions.cs
Labels: configuration

#4534 Fix publish-downloads.sh script
  scripts/deployment/publish-downloads.sh
Labels: devops

#4555 Enable WSL for tests, specifically for Ubuntu-22.04
  src/Nethermind/testenvironments.json
Labels: low priority
