Repository NethermindEth/nethermind, pull requests merged in 2023-02, with the labels that each got.

#4890 Add point evaluation precompile
  src/Nethermind/Nethermind.Core.Test/AddressTests.cs
  src/Nethermind/Nethermind.Core/Specs/ISpecProvider.cs
  src/Nethermind/Nethermind.Crypto/KzgPolynomialCommitments.cs
  src/Nethermind/Nethermind.Crypto/Nethermind.Crypto.csproj
  src/Nethermind/Nethermind.Crypto/kzg_trusted_setup.txt
  src/Nethermind/Nethermind.Evm.Test/PointEvaluationPrecompileTests.cs
  src/Nethermind/Nethermind.Evm/Metrics.cs
  src/Nethermind/Nethermind.Evm/Precompiles/AddressExtensions.cs
  src/Nethermind/Nethermind.Evm/Precompiles/PointEvaluationPrecompile.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Init/Steps/InitPrecompiles.cs
Labels: eip

#5210 Add withdrawals to `engine_getPayloadBodiesBy*` methods
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.HelperFunctions.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayloadBodyV1Result.cs
  src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Shanghai.cs
  src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/ExchangeCapabilitiesHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetPayloadBodiesByHashV1Handler.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetPayloadBodiesByRangeV1Handler.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/IGetPayloadBodiesByRangeV1Handler.cs
  src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.Shanghai.cs
  src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergeErrorCodes.cs
Labels: rpc

#5242 Remove `engine_executionStatus` method
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.HelperFunctions.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Synchronization.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionStatusResult.cs
  src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/ExchangeCapabilitiesHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/ExecutionStatusHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
Labels: rpc

#5241 Remove capabilities timeout and refactor
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
  src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/ExchangeCapabilitiesHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.cs
Labels: rpc

#5257 Revise last known block handling in `engine_getPayloadBodiesByRangeV1`
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetPayloadBodiesByRangeV1Handler.cs
Labels: rpc

#5258 Add session direction to sync peer report
  src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs
  src/Nethermind/Nethermind.Synchronization.Test/SyncPeersReportTests.cs
  src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs
Labels: minor

#5259 Trie node memory optimization
  src/Nethermind/Nethermind.Benchmark/Store/TrieNodeBenchmarks.cs
  src/Nethermind/Nethermind.Trie.Test/TrieNodeTests.cs
  src/Nethermind/Nethermind.Trie/NodeType.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
Labels: performance, trie

#5265 StorageCell byref
  src/Nethermind/Nethermind.AccountAbstraction/Executor/UserOperationTracer.cs
  src/Nethermind/Nethermind.Benchmark/State/StorageCellBenchmark.cs
  src/Nethermind/Nethermind.Evm.Test/TestAllTracerWithOutput.cs
  src/Nethermind/Nethermind.Evm/Tracing/AccessTxTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/AlwaysCancelTxTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/BlockReceiptsTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/CallOutputTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/CancellationTxTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/CompositeTxTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/EstimateGasTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/FeesTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/GasEstimator.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/NullTxTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeTxTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/Proofs/ProofTxTracer.cs
  src/Nethermind/Nethermind.Mev/BeneficiaryTracer.cs
  src/Nethermind/Nethermind.Mev/Execution/TxBundleSimulator.cs
  src/Nethermind/Nethermind.State.Test.Runner/StateTestTxTracer.cs
  src/Nethermind/Nethermind.State/IStorageProvider.cs
  src/Nethermind/Nethermind.State/IStorageTracer.cs
  src/Nethermind/Nethermind.State/NullStorageTracer.cs
  src/Nethermind/Nethermind.State/PartialStorageProviderBase.cs
  src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
  src/Nethermind/Nethermind.State/StorageProvider.cs
  src/Nethermind/Nethermind.State/TransientStorageProvider.cs
Labels: performance

#5270 Use input buffer directly for Sha256Precompile
  src/Nethermind/Nethermind.Evm/Precompiles/Sha256Precompile.cs
Labels: performance

#5269 Skip intermediate MemoryStream in EciesCipher.Encrypt
  src/Nethermind/Nethermind.Crypto/EciesCipher.cs
Labels: performance

#5277 .AsSpan().Slice(x,y) => .AsSpan(x,y)
  src/Nethermind/Nethermind.Consensus.Clique/SnapshotManager.cs
  src/Nethermind/Nethermind.Core/Crypto/Signature.cs
  src/Nethermind/Nethermind.Core/Extensions/ByteArrayExtensions.cs
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Crypto/EciesCipher.cs
  src/Nethermind/Nethermind.Crypto/OptimizedKdf.cs
  src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
  src/Nethermind/Nethermind.Evm/ZeroPaddedSpan.cs
  src/Nethermind/Nethermind.Network.Benchmark/InFlowBenchmarks.cs
  src/Nethermind/Nethermind.Network.Test/Rlpx/Handshake/EciesCipherTests.cs
  src/Nethermind/Nethermind.Network.Test/Rlpx/HobbitTests.cs
  src/Nethermind/Nethermind.Network.Test/Rlpx/TestWrappers/ZeroFrameDecoderTestWrapper.cs
  src/Nethermind/Nethermind.Network.Test/Rlpx/ZeroNettyFrameDecoderTests.cs
  src/Nethermind/Nethermind.Network/Rlpx/FrameMacProcessor.cs
  src/Nethermind/Nethermind.Network/Rlpx/Handshake/AckMessageSerializer.cs
  src/Nethermind/Nethermind.Network/Rlpx/Handshake/AuthMessageSerializer.cs
  src/Nethermind/Nethermind.Network/Rlpx/ZeroFrameDecoder.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
Labels: performance

#5275 Make ArrayPoolList.GuardIndex inlinable
  src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs
  src/Nethermind/Nethermind.Core/Collections/ByteArrayPoolList.cs
Labels: performance

#4865 Eip 4750/eof function sections
  src/Nethermind/Chains/shandong.json
  src/Nethermind/Nethermind.Benchmark/Evm/JumpDestinationsBenchmark.cs
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Core/Specs/IReleaseSpec.cs
  src/Nethermind/Nethermind.Evm.Test/BytecodeBuilderExtensionsTests.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EOF3540Tests.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EOF3670Tests.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EOF4200Tests.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EOF4750Tests.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EofTestsBase.cs
  src/Nethermind/Nethermind.Evm.Test/InvalidOpcodeTests.cs
  src/Nethermind/Nethermind.Evm.Test/VirtualMachineTestsBase.cs
  src/Nethermind/Nethermind.Evm/ByteCodeBuilderExtensions.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/CodeInfo.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/EofCodeInfo.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/ICodeInfo.cs
  src/Nethermind/Nethermind.Evm/EOF/EvmObjectFormat.cs
  src/Nethermind/Nethermind.Evm/EvmException.cs
  src/Nethermind/Nethermind.Evm/EvmState.cs
  src/Nethermind/Nethermind.Evm/GasCostOf.cs
  src/Nethermind/Nethermind.Evm/Instruction.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs.Test/OverridableReleaseSpec.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs
  src/Nethermind/Nethermind.Specs/Forks/15_Shanghai.cs
  src/Nethermind/Nethermind.Specs/ReleaseSpec.cs
  src/Nethermind/Nethermind.Specs/SystemTransactionReleaseSpec.cs
Labels: eip, shanghai, eof

#4864 Eip 4200/evm static relative jumps
  src/Nethermind/Chains/shandong.json
  src/Nethermind/Nethermind.Benchmark/Evm/JumpDestinationsBenchmark.cs
  src/Nethermind/Nethermind.Core/Extensions/BitArrayExtensions.cs
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Core/Extensions/RangeExtensions.cs
  src/Nethermind/Nethermind.Core/Specs/IReleaseSpec.cs
  src/Nethermind/Nethermind.Evm.Test/BytecodeBuilderExtensionsTests.cs
  src/Nethermind/Nethermind.Evm.Test/CodeAnalysis/CodeDataAnalyzerHelperTests.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EOF3540Tests.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EOF3670Tests.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EOF4200Tests.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EOF4750Tests.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EofTestsBase.cs
  src/Nethermind/Nethermind.Evm.Test/InstructionTests.cs
  src/Nethermind/Nethermind.Evm.Test/InvalidOpcodeTests.cs
  src/Nethermind/Nethermind.Evm.Test/VirtualMachineTestsBase.cs
  src/Nethermind/Nethermind.Evm/BitmapHelper.cs
  src/Nethermind/Nethermind.Evm/ByteCodeBuilderExtensions.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/CodeDataAnalyzer.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/CodeInfo.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/EofCodeInfo.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/ICodeInfo.cs
  src/Nethermind/Nethermind.Evm/CodeDepositHandler.cs
  src/Nethermind/Nethermind.Evm/EOF/EvmObjectFormat.cs
  src/Nethermind/Nethermind.Evm/EvmException.cs
  src/Nethermind/Nethermind.Evm/EvmState.cs
  src/Nethermind/Nethermind.Evm/GasCostOf.cs
  src/Nethermind/Nethermind.Evm/Instruction.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/TraceRpcModuleTests.cs
  src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs.Test/OverridableReleaseSpec.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs
  src/Nethermind/Nethermind.Specs/Forks/11_Berlin.cs
  src/Nethermind/Nethermind.Specs/Forks/15_Shanghai.cs
  src/Nethermind/Nethermind.Specs/ReleaseSpec.cs
  src/Nethermind/Nethermind.Specs/SystemTransactionReleaseSpec.cs
  src/Nethermind/Nethermind.Specs/TestSpecProvider.cs
Labels: eip, shanghai, eof

#5267 Trie node memory optimization fixed
  src/Nethermind/Nethermind.Benchmark/Store/TrieNodeBenchmarks.cs
  src/Nethermind/Nethermind.Trie.Test/TrieNodeTests.cs
  src/Nethermind/Nethermind.Trie/NodeType.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
Labels: performance

#5262 TrieNode further memory optimizations
  src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs
  src/Nethermind/Nethermind.Trie.Test/TrieNodeTests.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
Labels: performance

#5283 StorageTree opitimization
  src/Nethermind/Nethermind.Benchmark/State/StorageTreeBenchmark.cs
  src/Nethermind/Nethermind.State/Nethermind.State.csproj
  src/Nethermind/Nethermind.State/StorageTree.cs
Labels: performance

#5291 BouncyCastle.KeccakDigest => Nethermind.KeccakHash
  src/Nethermind/Nethermind.Core.Test/KeccakTests.cs
  src/Nethermind/Nethermind.Core/Crypto/KeccakHash.cs
  src/Nethermind/Nethermind.Crypto/Keccak512.cs
  src/Nethermind/Nethermind.Crypto/KeccakRlpStream.cs
  src/Nethermind/Nethermind.Network.Test/NetTestVectors.cs
  src/Nethermind/Nethermind.Network.Test/Rlpx/FrameMacProcessorTests.cs
  src/Nethermind/Nethermind.Network.Test/Rlpx/Handshake/EncryptionHandshakeServiceTests.cs
  src/Nethermind/Nethermind.Network/Rlpx/EncryptionSecrets.cs
  src/Nethermind/Nethermind.Network/Rlpx/FrameMacProcessor.cs
  src/Nethermind/Nethermind.Network/Rlpx/Handshake/HandshakeService.cs
  src/Nethermind/Nethermind.Network/Rlpx/IFrameMacProcessor.cs
  src/Nethermind/Nethermind.Network/Rlpx/NettyHandshakeHandler.cs
Labels: refactoring, performance, cryptography

#5178 Creating PPA Package for recent Ubuntu versions
  .github/workflows/release.yml
Labels: devops

#5320 Add hive-consensus-tests workflow and program to generate it
  .github/workflows/hive-consensus-tests.yml
  tools/HiveConsensusWorkflowGenerator/HiveConsensusWorkflowGenerator.csproj
  tools/HiveConsensusWorkflowGenerator/Program.cs
Labels: setup

#5346 Mark `engine_getPayloadBodiesBy*` methods as optional capabilities
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/EngineRpcCapabilitiesProvider.cs
Labels: rpc
