Repository NethermindEth/nethermind, pull requests merged in 2023-01, with the labels that each got.

#5067 EIP-3540 polish
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Core/Extensions/EnumExtensions.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EOF3540Tests.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EofTestsBase.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/ByteCodeValidator.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/CodeDataAnalyzer.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/CodeInfo.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/CodeInfoFactory.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/EofCodeInfo.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/ICodeInfo.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/JumpdestAnalyzer.cs
  src/Nethermind/Nethermind.Evm/CodeDepositHandler.cs
  src/Nethermind/Nethermind.Evm/EOF/EofHeader.cs
  src/Nethermind/Nethermind.Evm/EOF/EvmObjectFormat.cs
  src/Nethermind/Nethermind.Evm/EOF/EvmObjectFormatCodeInfoExtensions.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Specs.Test/OverridableReleaseSpec.cs
Labels: eof

#4921 Perf/Use readwrite lock with statesync
  src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedHealingTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTestsBase.cs
  src/Nethermind/Nethermind.Synchronization.Test/TrieScenarios.cs
  src/Nethermind/Nethermind.Synchronization/FastSync/BranchProgress.cs
  src/Nethermind/Nethermind.Synchronization/FastSync/PendingSyncItems.cs
  src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncItem.cs
  src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs
  src/Nethermind/Nethermind.Synchronization/StateSync/StateSyncDispatcher.cs
Labels: performance, low priority

#5086 Improve pre-release version deployment
  .github/workflows/release-nethermind.yml
  scripts/deployment/publish-github.sh
Labels: devops, release

#5117 Revise README
  README.md
Labels: docs

#5101 EIP 4200 : Use Bitmasks to catch Jump collisions
  src/Nethermind/Nethermind.Core/Extensions/BitArrayExtensions.cs
  src/Nethermind/Nethermind.Evm.Test/CodeAnalysis/CodeDataAnalyzerHelperTests.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EOF4200Tests.cs
  src/Nethermind/Nethermind.Evm.Test/EOFChecks/EofTestsBase.cs
  src/Nethermind/Nethermind.Evm/BitmapHelper.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/CodeDataAnalyzer.cs
  src/Nethermind/Nethermind.Evm/CodeDepositHandler.cs
  src/Nethermind/Nethermind.Evm/EOF/EvmObjectFormat.cs
  src/Nethermind/Nethermind.Evm/Instruction.cs
Labels: eof

#5121 Minor pipeline allocator cleanup
  src/Nethermind/Nethermind.Network.Test/Rlpx/Handshake/NettyHandshakeHandlerTests.cs
  src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroNettyP2PHandler.cs
  src/Nethermind/Nethermind.Network/Rlpx/NettyHandshakeHandler.cs
  src/Nethermind/Nethermind.Network/Rlpx/ZeroFrameDecoder.cs
  src/Nethermind/Nethermind.Network/Rlpx/ZeroFrameMerger.cs
Labels: minor

#5096 Consolidate scripts
  .github/workflows/release-nethermind.yml
  .gitmodules
  build/debian/compat
  build/debian/copyright
  scripts/deployment/debian/compat
  scripts/deployment/debian/control
  scripts/deployment/debian/copyright
  scripts/deployment/debian/postinst
  scripts/deployment/debian/prerm
  scripts/deployment/debian/rules
  scripts/deployment/publish-ppa.sh
Labels: devops

#5140 Disable eth68 for now because spec is not final
  src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
  src/Nethermind/Nethermind.Network/ProtocolsManager.cs
Labels: network

#5154 Unify Engine API failure responses
  src/Nethermind/Nethermind.Consensus/Producers/PayloadAttributes.cs
  src/Nethermind/Nethermind.Core/Specs/ForkActivation.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayload.cs
  src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Paris.cs
  src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Shanghai.cs
  src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.Paris.cs
  src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.Shanghai.cs
  src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
Labels: rpc, shanghai

#5182 Revise PPA copy scripts
  .github/workflows/release-nethermind.yml
  scripts/deployment/copy-ppa-packages-to-new-series.sh
  scripts/deployment/copy-ppa.sh
Labels: devops

#4867 Add specification, configs, new transaction type and header fields
  src/Nethermind/Chains/eip4844_local.json
  src/Nethermind/Nethermind.Blockchain.Test/Validators/TxValidatorTests.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
  src/Nethermind/Nethermind.Consensus/Producers/BlockProducerBase.cs
  src/Nethermind/Nethermind.Consensus/Validators/TxValidator.cs
  src/Nethermind/Nethermind.Core.Test/Builders/BlockHeaderBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Builders/TransactionBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Encoding/HeaderDecoderTests.cs
  src/Nethermind/Nethermind.Core.Test/Json/TxTypeConverterTests.cs
  src/Nethermind/Nethermind.Core.Test/Sources/TxTypeSource.cs
  src/Nethermind/Nethermind.Core/Block.cs
  src/Nethermind/Nethermind.Core/BlockHeader.cs
  src/Nethermind/Nethermind.Core/Specs/IReleaseSpec.cs
  src/Nethermind/Nethermind.Core/Transaction.cs
  src/Nethermind/Nethermind.Core/TxType.cs
  src/Nethermind/Nethermind.Evm.Test/InvalidOpcodeTests.cs
  src/Nethermind/Nethermind.Facade/BlockchainBridge.cs
  src/Nethermind/Nethermind.Facade/Proxy/Models/BlockModel.cs
  src/Nethermind/Nethermind.Hive/HiveRunner.cs
  src/Nethermind/Nethermind.Init/Steps/InitRlp.cs
  src/Nethermind/Nethermind.JsonRpc/Data/TransactionForRpc.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Eth/BlockForRpc.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayload.cs
  src/Nethermind/Nethermind.Network.Discovery/Serializers/NeighborsMsgSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/BlockBodiesMessageSerializer.cs
  src/Nethermind/Nethermind.Network/Rlpx/FrameHeaderReader.cs
  src/Nethermind/Nethermind.Runner/Properties/launchSettings.json
  src/Nethermind/Nethermind.Runner/configs/eip4844_local.cfg
  src/Nethermind/Nethermind.Serialization.Rlp/HeaderDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/ReceiptMessageDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpDecoderExtensions.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
  src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs.Test/MainnetSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs.Test/OverridableReleaseSpec.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs
  src/Nethermind/Nethermind.Specs/Forks/17_Cancun.cs
  src/Nethermind/Nethermind.Specs/MainNetSpecProvider.cs
  src/Nethermind/Nethermind.Specs/ReleaseSpec.cs
  src/Nethermind/Nethermind.Specs/SystemTransactionReleaseSpec.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
Labels: eip

#4894 Add DATAHASH opcode
  src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
  src/Nethermind/Nethermind.Core.Test/Nethermind.Core.Test.csproj
  src/Nethermind/Nethermind.Evm.Benchmark/EvmBenchmarks.cs
  src/Nethermind/Nethermind.Evm.Benchmark/MultipleUnsignedOperations.cs
  src/Nethermind/Nethermind.Evm.Benchmark/StaticCallBenchmarks.cs
  src/Nethermind/Nethermind.Evm.Test/Eip4844Tests.cs
  src/Nethermind/Nethermind.Evm.Test/InvalidOpcodeTests.cs
  src/Nethermind/Nethermind.Evm.Test/VirtualMachineTestsBase.cs
  src/Nethermind/Nethermind.Evm/ByteCodeBuilderExtensions.cs
  src/Nethermind/Nethermind.Evm/GasCostOf.cs
  src/Nethermind/Nethermind.Evm/Instruction.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.Evm/TxExecutionContext.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcBlockchain.cs
Labels: eip, evm

#5142 Revise and fix workflows failures on release
  .github/workflows/codeql.yml
  .github/workflows/discord-announcement.yml
  .github/workflows/hive-tests.yml
  .github/workflows/release.yml
  .github/workflows/run-discord-announcement.yml
  .github/workflows/run-merge-hive-tests.yml
  scripts/deployment/debian/postinst
  scripts/hive-results.sh
  scripts/testing/hiveTestResultPrinter.py
Labels: devops

#5196 Use hardware accelerated Aes on x64
  src/Nethermind/Nethermind.Crypto/AesEngineX86Intrinsic.cs
  src/Nethermind/Nethermind.Crypto/EciesCipher.cs
  src/Nethermind/Nethermind.Network/Rlpx/FrameCipher.cs
  src/Nethermind/Nethermind.Network/Rlpx/FrameMacProcessor.cs
Labels: cryptography

#5206 Optimize HexPrefix
  src/Nethermind/Ethereum.HexPrefix.Test/HexPrefixTests.cs
  src/Nethermind/Nethermind.Benchmark/Store/HexPrefixFromBytesBenchmarks.cs
  src/Nethermind/Nethermind.State.Test/SnapSync/Storage/SnapStorageTests.cs
  src/Nethermind/Nethermind.State/Proofs/AccountProofCollector.cs
  src/Nethermind/Nethermind.State/Proofs/ProofCollector.cs
  src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs
  src/Nethermind/Nethermind.Trie.Test/HexPrefixTests.cs
  src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs
  src/Nethermind/Nethermind.Trie.Test/TrieNodeTests.cs
  src/Nethermind/Nethermind.Trie/HexPrefix.cs
  src/Nethermind/Nethermind.Trie/Nethermind.Trie.csproj
  src/Nethermind/Nethermind.Trie/PatriciaTree.cs
  src/Nethermind/Nethermind.Trie/TreeDumper.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
  src/Nethermind/Nethermind.Trie/TrieNodeFactory.cs
Labels: performance

#5203 Remove INVALID_BLOCK_HASH
  src/Nethermind/Nethermind.Core/BlockHeader.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/NewPayloadV1Result.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/PayloadStatusV1.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/Statuses.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
Labels: rpc

#5212 Implement `engine_exchangeCapabilities` method
  src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
  src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/ExchangeCapabilitiesHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
Labels: rpc
