Repository NethermindEth/nethermind, pull requests merged in 2023-08, with the labels that each got.

#5981 Fix loading plugins with configs
  src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionPlugin.cs
  src/Nethermind/Nethermind.AuRa.Test/Contract/ContractDataStoreTests.cs
  src/Nethermind/Nethermind.Config.Test/ConfigFileTestsBase.cs
  src/Nethermind/Nethermind.Config/ConfigProvider.cs
  src/Nethermind/Nethermind.Core.Test/RateLimiterTests.cs
  src/Nethermind/Nethermind.Core/Extensions/TypeExtensions.cs
  src/Nethermind/Nethermind.Core/TypeDiscovery.cs
  src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs
  src/Nethermind/Nethermind.Init/Steps/StartMonitoring.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/BoundedModulePoolTests.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
  src/Nethermind/Nethermind.JsonRpc.Test/RpcTest.cs
  src/Nethermind/Nethermind.JsonRpc.TraceStore/TraceStorePlugin.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/BoundedModulePool.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/IRpcModuleProviderExtensions.cs
  src/Nethermind/Nethermind.Mev/MevPlugin.cs
  src/Nethermind/Nethermind.Monitoring.Test/MetricsTests.cs
  src/Nethermind/Nethermind.Runner/Program.cs
Labels: plugins

#5501 Implement `debug_standardTraceBlockToFile` method
  src/Nethermind/Directory.Packages.props
  src/Nethermind/Nethermind.Blockchain/LogTraceDumper.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
  src/Nethermind/Nethermind.Consensus/Tracing/GethStyleTracer.cs
  src/Nethermind/Nethermind.Consensus/Tracing/IGethStyleTracer.cs
  src/Nethermind/Nethermind.Core/Extensions/Int64Extensions.cs
  src/Nethermind/Nethermind.Core/Extensions/IntExtensions.cs
  src/Nethermind/Nethermind.Evm.Test/EvmMemoryTestsBase.cs
  src/Nethermind/Nethermind.Evm.Test/Nethermind.Evm.Test.csproj
  src/Nethermind/Nethermind.Evm.Test/Tracing/CompositeBlockTracerTests.cs
  src/Nethermind/Nethermind.Evm.Test/Tracing/DebugTracerTests.cs
  src/Nethermind/Nethermind.Evm.Test/Tracing/GethLikeBlockFileTracerTests.cs
  src/Nethermind/Nethermind.Evm.Test/Tracing/GethLikeBlockMemoryTracerTests.cs
  src/Nethermind/Nethermind.Evm.Test/Tracing/GethLikeBlockTracerTests.cs
  src/Nethermind/Nethermind.Evm.Test/Tracing/GethLikeTxFileTracerTests.cs
  src/Nethermind/Nethermind.Evm.Test/Tracing/GethLikeTxMemoryTracerTests.cs
  src/Nethermind/Nethermind.Evm.Test/Tracing/GethLikeTxTracerTests.cs
  src/Nethermind/Nethermind.Evm.Test/TransactionProcessorTests.cs
  src/Nethermind/Nethermind.Evm.Test/VirtualMachineTests.cs
  src/Nethermind/Nethermind.Evm.Test/VirtualMachineTestsBase.cs
  src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
  src/Nethermind/Nethermind.Evm/EvmStack.cs
  src/Nethermind/Nethermind.Evm/IEvmMemory.cs
  src/Nethermind/Nethermind.Evm/Tracing/AlwaysCancelTxTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/BlockReceiptsTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/BlockTracerBase.cs
  src/Nethermind/Nethermind.Evm/Tracing/CancellationTxTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/CompositeTxTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/Debugger/DebugTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeBlockFileTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeBlockMemoryTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeBlockTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxFileTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxMemoryTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxTrace.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxTraceJsonLinesConverter.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethTraceOptions.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethTxFileTraceEntry.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethTxMemoryTraceEntry.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethTxTraceEntry.cs
  src/Nethermind/Nethermind.Evm/Tracing/ITxTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/NullTxTracer.cs
  src/Nethermind/Nethermind.Evm/Tracing/TxTracer.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/DebugModuleTests.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugBridge.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugModuleFactory.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugRpcModule.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/GethLikeTxTraceConverter.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugBridge.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugRpcModule.cs
  src/Nethermind/Nethermind.Serialization.Json/ULongConverter.cs
  src/Nethermind/Nethermind.State.Test.Runner/StateTestTxTracer.cs
Labels: rpc, evm

#6039 Improve Nethermind executable rename handling
  Dockerfile
  Dockerfile.dev
  scripts/deployment/build-runner.sh
Labels: devops, release, high priority
