Repository NethermindEth/nethermind, pull requests merged in 2023-06, with the labels that each got.

#5747 Less aggressive peer discovery
  src/Nethermind/Nethermind.Core/Crypto/PublicKey.cs
  src/Nethermind/Nethermind.Network.Stats/Model/Node.cs
  src/Nethermind/Nethermind.Network.Stats/NodeStatsLight.cs
  src/Nethermind/Nethermind.Network.Stats/NodeStatsManager.cs
  src/Nethermind/Nethermind.Network/Peer.cs
  src/Nethermind/Nethermind.Network/PeerManager.cs
  src/Nethermind/Nethermind.Network/PeerPool.cs
Labels: performance

#5593 Add RLP encoding and hashing for Blob txs
  src/Nethermind/Nethermind.Blockchain.Test/Validators/TxValidatorTests.cs
  src/Nethermind/Nethermind.Cli/Console/ColorfulCliConsole.cs
  src/Nethermind/Nethermind.Consensus/Transactions/EmptyTxSource.cs
  src/Nethermind/Nethermind.Consensus/Transactions/FilteredTxSource.cs
  src/Nethermind/Nethermind.Consensus/Transactions/ITxSource.cs
  src/Nethermind/Nethermind.Consensus/Transactions/SinglePendingTxSelector.cs
  src/Nethermind/Nethermind.Consensus/Validators/TxValidator.cs
  src/Nethermind/Nethermind.Core.Test/AssertionsSetup.cs
  src/Nethermind/Nethermind.Core.Test/Builders/AccessListBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Builders/Build.AccessList.cs
  src/Nethermind/Nethermind.Core.Test/Builders/Build.Transaction.cs
  src/Nethermind/Nethermind.Core.Test/Builders/TestItem.cs
  src/Nethermind/Nethermind.Core.Test/Builders/TransactionBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Encoding/ShardBlobTxDecoderTests.TestCases.cs
  src/Nethermind/Nethermind.Core.Test/Encoding/ShardBlobTxDecoderTests.cs
  src/Nethermind/Nethermind.Core.Test/Encoding/TxDecoderTests.cs
  src/Nethermind/Nethermind.Core.Test/Nethermind.Core.Test.csproj
  src/Nethermind/Nethermind.Core.Test/TransactionTests.cs
  src/Nethermind/Nethermind.Core/Transaction.cs
  src/Nethermind/Nethermind.Crypto/EthereumEcdsa.cs
  src/Nethermind/Nethermind.Crypto/KzgPolynomialCommitments.cs
  src/Nethermind/Nethermind.Crypto/Nethermind.Crypto.csproj
  src/Nethermind/Nethermind.Crypto/TransactionExtensions.cs
  src/Nethermind/Nethermind.HealthChecks/DbDriveInfoProvider.cs
  src/Nethermind/Nethermind.JsonRpc/Data/TransactionForRpc.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/BlobsBundleV1.cs
  src/Nethermind/Nethermind.Merkleization/Merkle.Containers.cs
  src/Nethermind/Nethermind.Merkleization/Merkleizer.cs
  src/Nethermind/Nethermind.Network.Test/Nethermind.Network.Test.csproj
  src/Nethermind/Nethermind.Network.Test/P2P/SerializerTester.cs
  src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/BlockBodiesMessageSerializerTests.cs
  src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/TransactionsMessageSerializerTests.cs
  src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V65/PooledTransactionsMessageSerializerTests.cs
  src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V66/BlockBodiesMessageSerializerTests.cs
  src/Nethermind/Nethermind.Network.Test/Rlpx/HobbitTests.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/BlockBodiesMessage.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/TransactionsMessageSerializer.cs
  src/Nethermind/Nethermind.Serialization.Rlp/BlockDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpBehaviors.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
  src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs
  src/Nethermind/Nethermind.Serialization.Ssz/MiscDependencies/Ssz.Bytes32.cs
  src/Nethermind/Nethermind.Serialization.Ssz/Ssz.BasicTypes.cs
  src/Nethermind/Nethermind.State/Proofs/TxTrie.cs
  src/Nethermind/Nethermind.TxPool.Test/TxBroadcasterTests.cs
Labels: eip-4844

#5751 Reduce datetime calls in peer discovery by factor of 100
  src/Nethermind/Nethermind.Core/Crypto/PublicKey.cs
  src/Nethermind/Nethermind.Network.Benchmark/NodeStatsCtorBenchmarks.cs
  src/Nethermind/Nethermind.Network.Discovery.Test/RoutingTable/NodeBucketItemTests.cs
  src/Nethermind/Nethermind.Network.Discovery/DiscoveryApp.cs
  src/Nethermind/Nethermind.Network.Discovery/DiscoveryManager.cs
  src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeBucket.cs
  src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeBucketItem.cs
  src/Nethermind/Nethermind.Network.Stats/INodeStats.cs
  src/Nethermind/Nethermind.Network.Stats/Model/Node.cs
  src/Nethermind/Nethermind.Network.Stats/NodeStatsLight.cs
  src/Nethermind/Nethermind.Network.Stats/NodeStatsManager.cs
  src/Nethermind/Nethermind.Network.Test/NetworkStorageTests.cs
  src/Nethermind/Nethermind.Network.Test/NodeStatsTests.cs
  src/Nethermind/Nethermind.Network.Test/PeerManagerTests.cs
  src/Nethermind/Nethermind.Network/NetworkStorage.cs
  src/Nethermind/Nethermind.Network/Peer.cs
  src/Nethermind/Nethermind.Network/PeerManager.cs
  src/Nethermind/Nethermind.Network/ProtocolsManager.cs
Labels: performance

#5752 More efficient EvmPooledMemory
  src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
  src/Nethermind/Nethermind.Evm/EvmStack.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
Labels: performance

#5764 Boost Block Processor thread priority
  src/Nethermind/Nethermind.Consensus.Clique/CliqueBlockProducer.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
Labels: performance

#5772 Perf/release peer early
  src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncConfig.cs
  src/Nethermind/Nethermind.Blockchain/Synchronization/SyncConfig.cs
  src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
  src/Nethermind/Nethermind.Merge.Plugin/Synchronization/BeaconHeadersSyncDispatcher.cs
  src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloader.cs
  src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloaderFactory.cs
  src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeSynchronizer.cs
  src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.Merge.cs
  src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/FastSync/SnapProtocolTests/StateSyncDispatcherTester.cs
  src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTestsBase.cs
  src/Nethermind/Nethermind.Synchronization.Test/OldStyleFullSynchronizerTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/SyncDispatcherTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SyncThreadTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/IBlockDownloaderFactory.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncDispatcher.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/HeadersSyncDispatcher.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncDispatcher.cs
  src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/SnapSyncDispatcher.cs
  src/Nethermind/Nethermind.Synchronization/StateSync/StateSyncDispatcher.cs
  src/Nethermind/Nethermind.Synchronization/Synchronizer.cs
Labels: performance

#5779 Remove from ConcurrentDict directly rather than building secondary list
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
Labels: performance

#5780 Fix KeccaksIterator not working when some keccak zero prefix is not i…
  src/Nethermind/Nethermind.Blockchain.Test/Receipts/KeccaksIteratorTests.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/KeccaksIterator.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
Labels: bug

#5785 Perf/sync bodies with blobfiles
  src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncConfig.cs
  src/Nethermind/Nethermind.Blockchain/Synchronization/SyncConfig.cs
  src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
  src/Nethermind/Nethermind.Db/ITunableDb.cs
  src/Nethermind/Nethermind.Synchronization.Test/DbTuner/SyncDbTunerTests.cs
  src/Nethermind/Nethermind.Synchronization/DbTuner/SyncDbOptimizer.cs
Labels: performance

#5783 Add fast test for balance < tx.Value + gas
  src/Nethermind/Nethermind.TxPool/Filters/BalanceZeroFilter.cs
Labels: performance

#5781 Don't add Keccaks during cache pruning
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
Labels: bug

#5789 Optimize Snap sync + Sort DB Batches
  src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs
  src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/GetByteCodesMessageSerializer.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
  src/Nethermind/Nethermind.Synchronization/Nethermind.Synchronization.csproj
  src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/SnapSyncFeed.cs
  src/Nethermind/Nethermind.Trie/NibbleExtensions.cs
  src/Nethermind/Nethermind.Trie/PatriciaTree.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
Labels: performance

#5745 EIP-4844 V6 fixes and improvements
  src/Nethermind/Nethermind.Blockchain.Test/Validators/TxValidatorTests.cs
  src/Nethermind/Nethermind.Consensus/Validators/TxValidator.cs
  src/Nethermind/Nethermind.Core.Test/BytesTests.cs
  src/Nethermind/Nethermind.Core.Test/Encoding/ShardBlobTxDecoderTests.TestCases.cs
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Evm.Test/Eip4844Tests.cs
  src/Nethermind/Nethermind.Evm.Test/InvalidOpcodeTests.cs
  src/Nethermind/Nethermind.Evm/ByteCodeBuilderExtensions.cs
  src/Nethermind/Nethermind.Evm/GasCostOf.cs
  src/Nethermind/Nethermind.Evm/Instruction.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.HelperFunctions.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/BlobsBundleV1.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayload.cs
  src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Cancun.cs
  src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.Cancun.cs
  src/Nethermind/Nethermind.TxPool/TxPool.cs
Labels: eip-4844

#5802 Reuse batch Dictionary and skip empty batches
  src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
Labels: performance

#5801 Bugfix - exchangeCapabilites based on ChainSpec
  src/Nethermind/Nethermind.Core/Specs/ISpecProvider.cs
  src/Nethermind/Nethermind.HealthChecks.Test/NodeHealthServiceTests.cs
  src/Nethermind/Nethermind.HealthChecks/NodeHealthService.cs
  src/Nethermind/Nethermind.JsonRpc/IRpcCapabilitiesProvider.cs
  src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergeEngineModuleTests.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.PayloadProduction.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.RelayBuilder.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/EngineRpcCapabilitiesProvider.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/ExchangeCapabilitiesHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
Labels: bug

#5770 Improved colour logs + block tx gas gwei range
  src/Nethermind/Directory.Packages.props
  src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncPeer.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockValidationTransactionsExecutor.cs
  src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
  src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
  src/Nethermind/Nethermind.Evm/Metrics.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Init/MemoryHintMan.cs
  src/Nethermind/Nethermind.Init/Steps/Migrations/BloomMigration.cs
  src/Nethermind/Nethermind.Init/Steps/Migrations/ReceiptMigration.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/ForkchoiceStateV1.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/Synchronization/PeerRefresher.cs
  src/Nethermind/Nethermind.Merge.Plugin/Synchronization/PivotUpdator.cs
  src/Nethermind/Nethermind.Runner/NLog.config
  src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTestsBase.cs
  src/Nethermind/Nethermind.Synchronization.Test/LatencySyncPeerMock.cs
  src/Nethermind/Nethermind.Synchronization.Test/SyncPeerMock.cs
  src/Nethermind/Nethermind.Synchronization.Test/SyncPeerPoolTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SyncPeersReportTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SyncReportTest.cs
  src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs
  src/Nethermind/Nethermind.Synchronization/FastSync/DetailedProgress.cs
  src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
  src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs
  src/Nethermind/Nethermind.Synchronization/Reporting/SyncReport.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/Pivot.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs
  src/Nethermind/Nethermind.Trie/Pruning/MemoryLimit.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
  src/Nethermind/Nethermind.TxPool/TxPool.cs
Labels: logging

#5824 Fixed eip2537 activation
  src/Nethermind/Nethermind.Merge.Plugin.Test/ChainSpecBasedSpecProviderTests.TheMerge.cs
  src/Nethermind/Nethermind.Specs.Test/ChainParametersTests.cs
  src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs
Labels: bug

#5830 Revert colors in Hive tests
  .github/workflows/hive-consensus-tests.yml
  .github/workflows/hive-tests.yml
  src/Nethermind/Nethermind.Runner/NLog.config
Labels: bug

#5826 Reduce Evm Stackspace clearing
  src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
  src/Nethermind/Nethermind.Core/Buffers/LargerArrayPool.cs
  src/Nethermind/Nethermind.Evm.Benchmark/EvmBenchmarks.cs
  src/Nethermind/Nethermind.Evm.Benchmark/EvmStackBenchmarks.cs
  src/Nethermind/Nethermind.Evm.Benchmark/MultipleUnsignedOperations.cs
  src/Nethermind/Nethermind.Evm.Benchmark/StaticCallBenchmarks.cs
  src/Nethermind/Nethermind.Evm.Test/CmpTests.cs
  src/Nethermind/Nethermind.Evm.Test/SimdTests.cs
  src/Nethermind/Nethermind.Evm/ByteArrayExtensions.cs
  src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
  src/Nethermind/Nethermind.Evm/EvmStack.cs
  src/Nethermind/Nethermind.Evm/EvmState.cs
  src/Nethermind/Nethermind.Evm/IVirtualMachine.cs
  src/Nethermind/Nethermind.Evm/Metrics.cs
  src/Nethermind/Nethermind.Evm/Tracing/ITxTracer.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
Labels: performance

#5838 Add missing peer types to limits
  src/Nethermind/Nethermind.Network.Stats/Model/Node.cs
  src/Nethermind/Nethermind.Network.Stats/Model/NodeClientType.cs
  src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloaderLimits.cs
Labels: bug

#5840 Only output Changing state if state actually changes
  src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
Labels: logging

#5841 Don't use decimal percentages in peers report
  src/Nethermind/Nethermind.Runner/NLog.config
  src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs
Labels: logging

#5842 Adjust snap request threshold
  src/Nethermind/Nethermind.Synchronization.Test/SnapSync/ProgressTrackerTests.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs
Labels: minor

#5849 Don't use DarkGray
  src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
  src/Nethermind/Nethermind.Runner/NLog.config
Labels: logging

#5848 Add Gnosis Shanghai hard-fork timestamp
  src/Nethermind/Chains/gnosis.json
  src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs
  src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs/GnosisSpecProvider.cs
Labels: configuration, gnosis

#5854 Prefer code from code cache for Create
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.State/StateProvider.cs
Labels: performance

#5858 Pass ProcessingBranch via in
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
Labels: performance

#5791 Add MCopy to Evm
  src/Nethermind/Ethereum.Blockchain.Test/Eip5656Tests.cs
  src/Nethermind/Ethereum.Blockchain.Test/Ethereum.Blockchain.Test.csproj
  src/Nethermind/Ethereum.Test.Base/LoadEipTestsStrategy.cs
  src/Nethermind/Nethermind.Core/Specs/IReleaseSpec.cs
  src/Nethermind/Nethermind.Evm.Test/InstructionTests.cs
  src/Nethermind/Nethermind.Evm.Test/InvalidOpcodeTests.cs
  src/Nethermind/Nethermind.Evm.Test/Tracing/DebugTracerTests.cs
  src/Nethermind/Nethermind.Evm.Test/VirtualMachineTests.cs
  src/Nethermind/Nethermind.Evm.Test/VirtualMachineTestsBase.cs
  src/Nethermind/Nethermind.Evm/ByteCodeBuilderExtensions.cs
  src/Nethermind/Nethermind.Evm/Instruction.cs
  src/Nethermind/Nethermind.Evm/Metrics.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Specs.Test/OverridableReleaseSpec.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs
  src/Nethermind/Nethermind.Specs/Forks/16_Cancun.cs
  src/Nethermind/Nethermind.Specs/ReleaseSpec.cs
  src/Nethermind/Nethermind.Specs/SystemTransactionReleaseSpec.cs
Labels: evm, cancun

#5867 Skip alloc for zero sstore
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
Labels: performance

#5870 Receipt clean up in batch
  src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
Labels: performance, minor
