Repository NethermindEth/nethermind, pull requests merged in 2023-09, with the labels that each got.

#6073 Adjust name of cli assembly in docs generator
  src/Nethermind/Nethermind.GitBook/RpcAndCliDataProvider.cs
Labels: docs

#6077 Fix typo in docs
  src/Nethermind/Nethermind.JsonRpc/Modules/Trace/ITraceRpcModule.cs
Labels: docs

#6063 Fix read write metric snot updated
  src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs
Labels: minor

#6058 Publish draft releases as the latest
  scripts/deployment/publish-github.sh
Labels: devops

#6095 Fix symlinks for macOS packages
  scripts/deployment/archive-packages.sh
Labels: release

#6123 fix AggregateException being thrown instead of TimeoutException
  src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroProtocolHandlerBase.cs
Labels: minor

#5991 Fix PPA package post-install script
  scripts/deployment/debian/postinst
  scripts/execution.sh
Labels: devops, needed in 1.21.0

#6141 Update README
  README.md
Labels: docs
