Repository NethermindEth/nethermind, pull requests merged in 2023-04, with the labels that each got.

#5475 Perf/batched trie visitor
  src/Nethermind/Nethermind.Blockchain.Test/FullPruning/CopyTreeVisitorTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPrunerTests.cs
  src/Nethermind/Nethermind.Blockchain/FullPruning/FullPruner.cs
  src/Nethermind/Nethermind.Core.Test/Collections/CompactStackTests.cs
  src/Nethermind/Nethermind.Core/Collections/CompactStack.cs
  src/Nethermind/Nethermind.Core/Crypto/Keccak.cs
  src/Nethermind/Nethermind.Core/Nethermind.Core.csproj
  src/Nethermind/Nethermind.Db/IPruningConfig.cs
  src/Nethermind/Nethermind.Db/PruningConfig.cs
  src/Nethermind/Nethermind.Runner/configs/goerli.cfg
  src/Nethermind/Nethermind.Runner/configs/mainnet.cfg
  src/Nethermind/Nethermind.State/IStateProviderExtensions.cs
  src/Nethermind/Nethermind.Trie.Test/TrieNodeResolverWithReadFlagsTests.cs
  src/Nethermind/Nethermind.Trie/BatchedTrieVisitor.cs
  src/Nethermind/Nethermind.Trie/PatriciaTree.cs
  src/Nethermind/Nethermind.Trie/Pruning/ITrieNodeResolver.cs
  src/Nethermind/Nethermind.Trie/Pruning/NullTrieNodeResolver.cs
  src/Nethermind/Nethermind.Trie/Pruning/NullTrieStore.cs
  src/Nethermind/Nethermind.Trie/Pruning/ReadOnlyTrieStore.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs
  src/Nethermind/Nethermind.Trie/TrieNodeResolverWithReadFlags.cs
  src/Nethermind/Nethermind.Trie/VisitContext.cs
  src/Nethermind/Nethermind.Trie/VisitingOptions.cs
Labels: performance

#5539 Vectorize HexConverter.TryDecodeFromUtf16
  src/Nethermind/Nethermind.Benchmark/Core/FromHexBenchmarks.cs
  src/Nethermind/Nethermind.Core/Collections/ThrowHelper.cs
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Core/Extensions/HexConverter.cs
Labels: performance

#5473 EIP-4844 Transaction validation
  src/Nethermind/Directory.Packages.props
  src/Nethermind/Nethermind.Blockchain.Test/TransactionSelectorTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/Validators/ShardBlobBlockValidatorTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/Validators/TxValidatorTests.cs
  src/Nethermind/Nethermind.Consensus.AuRa/Contracts/TransactionPermissionContractV3.cs
  src/Nethermind/Nethermind.Consensus.AuRa/Transactions/TransactionExtensions.cs
  src/Nethermind/Nethermind.Consensus/Producers/TxPoolTxSource.cs
  src/Nethermind/Nethermind.Consensus/Validators/BlockValidator.cs
  src/Nethermind/Nethermind.Consensus/Validators/TxValidator.cs
  src/Nethermind/Nethermind.Core.Test/Builders/BlockBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Builders/TransactionBuilder.cs
  src/Nethermind/Nethermind.Core.Test/TransactionEipsSupportTests.cs
  src/Nethermind/Nethermind.Core.Test/TransactionTests.cs
  src/Nethermind/Nethermind.Core/Eip4844Constants.cs
  src/Nethermind/Nethermind.Core/Transaction.cs
  src/Nethermind/Nethermind.Core/TransactionExtensions.cs
  src/Nethermind/Nethermind.Crypto/KzgPolynomialCommitments.cs
  src/Nethermind/Nethermind.Evm/Precompiles/PointEvaluationPrecompile.cs
  src/Nethermind/Nethermind.Init/Steps/InitializePrecompiles.cs
  src/Nethermind/Nethermind.Init/Steps/StartBlockProducer.cs
  src/Nethermind/Nethermind.JsonRpc/Data/TransactionForRpc.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
  src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
  src/Nethermind/Nethermind.TxPool/Comparison/CompareReplacedTxByFee.cs
  src/Nethermind/Nethermind.TxPool/TransactionExtensions.cs
  src/Nethermind/Nethermind.TxPool/TxPool.cs
Labels: eip-4844

#5531 Perf/Reduce receipts db size
  src/Nethermind/Nethermind.Api/IInitConfig.cs
  src/Nethermind/Nethermind.Api/InitConfig.cs
  src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/Receipts/ReceiptsRecoveryTests.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/FullInfoReceiptFinder.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/IReceiptsRecovery.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/InMemoryReceiptStorage.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsIterator.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsRecovery.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsRecoveryResult.cs
  src/Nethermind/Nethermind.Core.Test/Builders/ReceiptBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Builders/TransactionBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Encoding/CompactReceiptStorageDecoderTests.cs
  src/Nethermind/Nethermind.Core.Test/Encoding/ReceiptArrayDecoderTests.cs
  src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Core/TransactionReceipt.cs
  src/Nethermind/Nethermind.Facade/Filters/LogFinder.cs
  src/Nethermind/Nethermind.Init/Steps/InitializeBlockTree.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Proof/ProofModuleFactory.cs
  src/Nethermind/Nethermind.Serialization.Rlp/CompactLogEntryDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/CompactReceiptStorageDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/ReceiptArrayStorageDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
  src/Nethermind/Nethermind.TxPool.Test/ReceiptStorageTests.cs
Labels: performance

#5547 Less invasive CPU logging
  src/Nethermind/Directory.Packages.props
  src/Nethermind/Nethermind.Init/Cpu/ConsoleExitHandler.cs
  src/Nethermind/Nethermind.Init/Cpu/CpuInfo.cs
  src/Nethermind/Nethermind.Init/Cpu/DefaultCultureInfo.cs
  src/Nethermind/Nethermind.Init/Cpu/Frequency.cs
  src/Nethermind/Nethermind.Init/Cpu/FrequencyUnit.cs
  src/Nethermind/Nethermind.Init/Cpu/ProcCpuInfoKeyNames.cs
  src/Nethermind/Nethermind.Init/Cpu/ProcCpuInfoParser.cs
  src/Nethermind/Nethermind.Init/Cpu/ProcCpuInfoProvider.cs
  src/Nethermind/Nethermind.Init/Cpu/ProcessExtensions.cs
  src/Nethermind/Nethermind.Init/Cpu/ProcessHelper.cs
  src/Nethermind/Nethermind.Init/Cpu/RuntimeInformation.cs
  src/Nethermind/Nethermind.Init/Cpu/SectionsHelper.cs
  src/Nethermind/Nethermind.Init/Cpu/SysctlCpuInfoParser.cs
  src/Nethermind/Nethermind.Init/Cpu/SysctlCpuInfoProvider.cs
  src/Nethermind/Nethermind.Init/Cpu/TimeInterval.cs
  src/Nethermind/Nethermind.Init/Cpu/TimeUnit.cs
  src/Nethermind/Nethermind.Init/Cpu/UnitPresentation.cs
  src/Nethermind/Nethermind.Init/Cpu/WmicCpuInfoKeyNames.cs
  src/Nethermind/Nethermind.Init/Cpu/WmicCpuInfoParser.cs
  src/Nethermind/Nethermind.Init/Cpu/WmicCpuInfoProvider.cs
  src/Nethermind/Nethermind.Init/Nethermind.Init.csproj
  src/Nethermind/Nethermind.Init/Steps/LogHardwareInfo.cs
Labels: bug

#5560 Perf/finalized txhash mapping encoding
  src/Nethermind/Nethermind.Api/IInitConfig.cs
  src/Nethermind/Nethermind.Api/InitConfig.cs
  src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/IReceiptConfig.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptConfig.cs
  src/Nethermind/Nethermind.Init/Steps/InitializeBlockTree.cs
  src/Nethermind/Nethermind.Init/Steps/MigrateConfigs.cs
  src/Nethermind/Nethermind.Init/Steps/Migrations/ReceiptMigration.cs
  src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/Migrations/ReceiptMigrationTests.cs
  src/Nethermind/Nethermind.TxPool.Test/ReceiptStorageTests.cs
Labels: performance

#5566 Update Final Total Difficulty for archive nodes
  src/Nethermind/Nethermind.Runner/configs/chiado_archive.cfg
  src/Nethermind/Nethermind.Runner/configs/gnosis_archive.cfg
  src/Nethermind/Nethermind.Runner/configs/goerli_archive.cfg
  src/Nethermind/Nethermind.Runner/configs/mainnet_archive.cfg
  src/Nethermind/Nethermind.Runner/configs/sepolia_archive.cfg
Labels: configs

#5575 Use Environment.TickCount64 rather than StopWatch.GetTimestamp
  src/Nethermind/Nethermind.Merge.Plugin/GC/GCKeeper.cs
Labels: bug

#5587 Include withdrawals in payload id computation
  src/Nethermind/Nethermind.Consensus/Producers/PayloadAttributes.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs
  src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs
Labels: bug

#5569 Perf/eth getlogs with compact encoding
  src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/Receipts/ReceiptsIteratorTests.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/KeccaksIterator.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/LogEntriesIterator.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsIterator.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsRecovery.cs
  src/Nethermind/Nethermind.Core.Test/Builders/BlockBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Encoding/CompactReceiptStorageDecoderTests.cs
  src/Nethermind/Nethermind.Core.Test/Encoding/LogEntryDecoderTests.cs
  src/Nethermind/Nethermind.Facade/Filters/LogFinder.cs
  src/Nethermind/Nethermind.Facade/Filters/Topics/AnyTopicsFilter.cs
  src/Nethermind/Nethermind.Facade/Filters/Topics/SequenceTopicsFilter.cs
  src/Nethermind/Nethermind.Serialization.Rlp/CompactLogEntryDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/CompactReceiptStorageDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/IReceiptRefDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/ReceiptArrayStorageDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/ReceiptStorageDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
Labels: performance

#5599 Return a couple additional ArrayPoolLists
  src/Nethermind/Nethermind.Abi.Test/AbiTests.cs
  src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs
  src/Nethermind/Nethermind.Core/Resettables/Resettable.cs
  src/Nethermind/Nethermind.Trie/BatchedTrieVisitor.cs
Labels: bug

#5605 Use direct properties rather than Linq
  src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockFinalizationManager.cs
  src/Nethermind/Nethermind.JsonRpc/JsonRpcUrl.cs
  src/Nethermind/Nethermind.Network/PeerManager.cs
  src/Nethermind/Nethermind.Runner/Program.cs
  src/Nethermind/Nethermind.Synchronization/Peers/AllocationStrategies/BySpeedStrategy.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs
Labels: performance

#5610 Replace `Nethermind.Secp256k1` with a NuGet package
  .github/workflows/build-secp256k1-libs.yml
  .github/workflows/nethermind-tests-codecov.yml
  .github/workflows/nethermind-tests.yml
  Dockerfile.secp256k1
  src/Nethermind/Benchmarks.sln
  src/Nethermind/Directory.Packages.props
  src/Nethermind/EthereumTests.sln
  src/Nethermind/Nethermind.Consensus/Signer.cs
  src/Nethermind/Nethermind.Core.Test/Crypto/SignatureTests.cs
  src/Nethermind/Nethermind.Core/Crypto/CompressedPublicKey.cs
  src/Nethermind/Nethermind.Core/Nethermind.Core.csproj
  src/Nethermind/Nethermind.Crypto/Ecdsa.cs
  src/Nethermind/Nethermind.Crypto/EciesCipher.cs
  src/Nethermind/Nethermind.Crypto/EthereumEcdsa.cs
  src/Nethermind/Nethermind.Crypto/PrivateKey.cs
  src/Nethermind/Nethermind.Crypto/PrivateKeyGenerator.cs
  src/Nethermind/Nethermind.Network.Benchmark/EcdhAgreementBenchmarks.cs
  src/Nethermind/Nethermind.Network.Benchmark/Nethermind.Network.Benchmark.csproj
  src/Nethermind/Nethermind.Network.Test/Crypto/BouncyCryptoTests.cs
  src/Nethermind/Nethermind.Network/Rlpx/Handshake/HandshakeService.cs
  src/Nethermind/Nethermind.Secp256k1.Test/Nethermind.Secp256k1.Test.csproj
  src/Nethermind/Nethermind.Secp256k1.Test/ProxyTests.cs
  src/Nethermind/Nethermind.Secp256k1/Nethermind.Secp256k1.csproj
  src/Nethermind/Nethermind.Secp256k1/Proxy.cs
  src/Nethermind/Nethermind.Secp256k1/runtimes/linux-arm/native/libsecp256k1.so
  src/Nethermind/Nethermind.Secp256k1/runtimes/linux-arm64/native/libsecp256k1.so
  src/Nethermind/Nethermind.Secp256k1/runtimes/linux-x64/native/libsecp256k1.so
  src/Nethermind/Nethermind.Secp256k1/runtimes/osx-arm64/native/libsecp256k1.dylib
  src/Nethermind/Nethermind.Secp256k1/runtimes/osx-x64/native/libsecp256k1.dylib
  src/Nethermind/Nethermind.Secp256k1/runtimes/win-x64/native/secp256k1.dll
  src/Nethermind/Nethermind.Wallet/DevKeyStoreWallet.cs
  src/Nethermind/Nethermind.Wallet/DevWallet.cs
  src/Nethermind/Nethermind.Wallet/ProtectedKeyStoreWallet.cs
  src/Nethermind/Nethermind.sln
  src/Nethermind/nuget.config
Labels: refactoring, performance

#5612 Replace `System.IO.Abstractions` with `TestableIO.System.IO.Abstractions.Wrappers` package
  src/Nethermind/Directory.Packages.props
  src/Nethermind/Nethermind.Blockchain/Nethermind.Blockchain.csproj
  src/Nethermind/Nethermind.Db/Nethermind.Db.csproj
  src/Nethermind/Nethermind.Hive/Nethermind.Hive.csproj
  src/Nethermind/Nethermind.JsonRpc/Nethermind.JsonRpc.csproj
  src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
  src/Nethermind/Nethermind.TxPool/Nethermind.TxPool.csproj
  src/Nethermind/Nethermind.Wallet/Nethermind.Wallet.csproj
Labels: refactoring

#5588 Feature/low priority write
  src/Nethermind/Nethermind.Blockchain.Test/FullPruning/CopyTreeVisitorTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPrunerTests.cs
  src/Nethermind/Nethermind.Blockchain/FullPruning/CopyTreeVisitor.cs
  src/Nethermind/Nethermind.Core.Test/InMemoryBatch.cs
  src/Nethermind/Nethermind.Core.Test/TestMemDb.cs
  src/Nethermind/Nethermind.Core/FakeBatch.cs
  src/Nethermind/Nethermind.Core/IKeyValueStore.cs
  src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs
  src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
  src/Nethermind/Nethermind.Db.Rpc/RpcDb.cs
  src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs
  src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs
  src/Nethermind/Nethermind.Db/MemDb.cs
  src/Nethermind/Nethermind.Db/NullDb.cs
  src/Nethermind/Nethermind.Db/ReadOnlyDb.cs
  src/Nethermind/Nethermind.Db/SimpleFilePublicKeyDb.cs
  src/Nethermind/Nethermind.State/Witnesses/WitnessingStore.cs
  src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs
  src/Nethermind/Nethermind.Trie/CachingStore.cs
  src/Nethermind/Nethermind.Trie/NullKeyValueStore.cs
  src/Nethermind/Nethermind.Trie/Pruning/NullTrieStore.cs
Labels: performance

#5614 Refactor and remove obsolete stuff
  scripts/deployment/build-runner.sh
  src/Nethermind/Chains/shandong.json
  src/Nethermind/Chains/withdrawals_devnet.json
  src/Nethermind/Chains/withdrawals_hivetests.json
  src/Nethermind/Chains/withdrawals_test.json
  src/Nethermind/Chains/zhejiang.json
  src/Nethermind/Directory.Packages.props
  src/Nethermind/Nethermind.Abi.Contracts/Contract.ConstantContract.cs
  src/Nethermind/Nethermind.Abi.Contracts/Contract.cs
  src/Nethermind/Nethermind.Abi.Contracts/Nethermind.Abi.Contracts.csproj
  src/Nethermind/Nethermind.Benchmark/Nethermind.Benchmark.csproj
  src/Nethermind/Nethermind.Blockchain.Test/Specs/shanghai_from_genesis.json
  src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs
  src/Nethermind/Nethermind.Runner/Data/UTC--2020-03-20T18-10-57.499744000Z--c7f8522f15c189e00d2f895b4528b4f84516cd7b
  src/Nethermind/Nethermind.Runner/Data/UTC--2020-03-20T18-15-53.949603000Z--5d55020e862bc876c8d2e9a4eeeda935ce6438c6
  src/Nethermind/Nethermind.Runner/Data/genesis.json
  src/Nethermind/Nethermind.Runner/Data/static-nodes-baseline-hosts.json
  src/Nethermind/Nethermind.Runner/Data/static-nodes-baseline.json
  src/Nethermind/Nethermind.Runner/Data/static-nodes-ndm-local.json
  src/Nethermind/Nethermind.Runner/Dockerfile
  src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
  src/Nethermind/Nethermind.Runner/Properties/PublishProfiles/FolderProfile.pubxml
  src/Nethermind/Nethermind.Runner/Properties/launchSettings.json
  src/Nethermind/Nethermind.Runner/configs/sepolia_archive.cfg
  src/Nethermind/Nethermind.Runner/configs/withdrawals_devnet.cfg
  src/Nethermind/Nethermind.Runner/configs/withdrawals_hivetests.cfg
  src/Nethermind/Nethermind.Runner/configs/zhejiang.cfg
  src/Nethermind/Nethermind.Runner/configs/zhejiang_archive.cfg
  src/Nethermind/Nethermind.Serialization.Ssz.Test/BitArrayTests.cs
  src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
Labels: refactoring

#5485 Refactor broadcasting for a needs of 4844
  src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandlerTests.cs
  src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandlerTests.cs
  src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandlerTests.cs
  src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandler.cs
  src/Nethermind/Nethermind.TxPool.Test/TxBroadcasterTests.cs
  src/Nethermind/Nethermind.TxPool/TransactionExtensions.cs
  src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs
Labels: network, eip-4844

#5618 Update security policy
  README.md
  SECURITY.md
Labels: security, docs

#5578 Fix/Rocksdb cache not set
  src/Nethermind/Nethermind.Db.Rocks/ColumnsDb.cs
  src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs
  src/Nethermind/Nethermind.Db.Rocks/Config/IDbConfig.cs
  src/Nethermind/Nethermind.Db.Rocks/Config/PerTableDbConfig.cs
  src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
  src/Nethermind/Nethermind.Db.Rocks/RocksDbFactory.cs
  src/Nethermind/Nethermind.Init/MemoryHintMan.cs
  src/Nethermind/Nethermind.Runner.Test/MemoryHintManTests.cs
Labels: performance
