Repository NethermindEth/nethermind, pull requests merged in 2023-05, with the labels that each got.

#5497 Shouldn't Wait() on timer threads
  src/Nethermind/Nethermind.Core/Extensions/TaskExtensions.cs
  src/Nethermind/Nethermind.Network.Discovery/DiscoveryApp.cs
  src/Nethermind/Nethermind.Network/PeerPool.cs
  src/Nethermind/Nethermind.Network/SessionMonitor.cs
  src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
  src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs
Labels: performance

#5641 Rename WriteBytesPerSec to BytesPerSec and add direct io flag.
  src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs
  src/Nethermind/Nethermind.Db.Rocks/Config/IDbConfig.cs
  src/Nethermind/Nethermind.Db.Rocks/Config/PerTableDbConfig.cs
  src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
Labels: minor

#5498 Compressing db
  src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPrunerTests.cs
  src/Nethermind/Nethermind.Db.Test/CompressingStoreTests.cs
  src/Nethermind/Nethermind.Db/CompressingDb.cs
  src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs
  src/Nethermind/Nethermind.Db/StandardDbInitializer.cs
  src/Nethermind/Nethermind.Synchronization.Test/TrieScenarios.cs
  src/Nethermind/Nethermind.Trie/CachingStore.cs
Labels: performance, difficult, database

#5656 Boost and fix tests
  .github/workflows/nethermind-tests-codecov.yml
  .github/workflows/nethermind-tests.yml
  src/Nethermind/Nethermind.Hive.Test/HivePluginTests.cs
  src/Nethermind/Nethermind.Hive.Test/Nethermind.Hive.Test.csproj
  src/Nethermind/Nethermind.Hive.Test/PluginTests.cs
  src/Nethermind/Nethermind.JsonRpc.TraceStore.Test/DbPersistingBlockTracerTests.cs
  src/Nethermind/Nethermind.JsonRpc.TraceStore.Test/Nethermind.JsonRpc.TraceStore.Test.csproj
  src/Nethermind/Nethermind.JsonRpc.TraceStore.Test/TraceSerializerTests.cs
  src/Nethermind/Nethermind.JsonRpc.TraceStore.Test/TraceStorePrunerTests.cs
  src/Nethermind/Nethermind.JsonRpc.TraceStore.Test/TraceStoreRpcModuleTests.cs
  src/Nethermind/Nethermind.JsonRpc.TraceStore.Test/xdai-17600039.json
  src/Nethermind/Nethermind.Network.Test/Rlpx/ZeroNettyFrameDecoderTests.cs
  src/Nethermind/Nethermind.Network.Test/Rlpx/ZeroNettyPacketSplitterTests.cs
  src/Nethermind/Nethermind.Network.Test/SnapProtocolHandlerTests.cs
  src/Nethermind/Nethermind.sln
Labels: refactoring, devops, test

#5678 Fix tests workflow jobs re-run handling
  .github/workflows/nethermind-tests.yml
Labels: devops, test

#5688 Add Shanghai hard-fork settings for Chiado testnet
  src/Nethermind/Chains/chiado.json
  src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs
  src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs/ChiadoSpecProvider.cs
  src/Nethermind/Nethermind.Specs/MainnetSpecProvider.cs
Labels: configuration, gnosis

#5149 Eof : refactors and optimizations
  src/Nethermind/Nethermind.Evm/AddressExtensions.cs
  src/Nethermind/Nethermind.Evm/BitmapHelper.cs
  src/Nethermind/Nethermind.Evm/EOF/EvmObjectFormat.cs
  src/Nethermind/Nethermind.Evm/Instruction.cs
Labels: refactoring, eof

#5703 Fix to publish the latest stable release only
  .github/workflows/publish-nuget.yml
  .github/workflows/publish-packages.yml
Labels: devops, release

#5712 Fix workflows triggering on release publish
  .github/workflows/build-nethermind-packages.yml
  .github/workflows/release.yml
  scripts/deployment/build-cli.sh
  scripts/deployment/build-launcher.sh
  scripts/deployment/build-runner.sh
  scripts/deployment/publish-downloads.sh
  scripts/deployment/publish-github.sh
Labels: devops, release

#5721 Don't apply EXTCODESIZE optimization if tracing
  src/Nethermind/Nethermind.Evm.Test/Tracing/GethLikeTxTracerTests.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
Labels: bug

#5728 Revise README
  README.md
  SECURITY.md
Labels: docs

#5724 Fixed pivot-related edge case that could lead to node corruption
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Synchronization.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
Labels: bug

#5733 Update `Nethermind.Crypto.SecP256k1` package
  src/Nethermind/Directory.Packages.props
Labels: bug, include in 1.19.0

#5710 Fix stuck state from period offline
  src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
Labels: bug, include in 1.19.0

#5735 Keccaks: Skip unneeded array allocations
  src/Nethermind/Nethermind.Consensus.Ethash/Ethash.cs
  src/Nethermind/Nethermind.Core/Crypto/Keccak.cs
  src/Nethermind/Nethermind.Evm/Precompiles/EcRecoverPrecompile.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Network/Rlpx/Handshake/AuthMessageSerializer.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
  src/Nethermind/Nethermind.State/Witnesses/WitnessingStore.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs
Labels: performance

#5737 Less contention for OldReceipts and OldBodies
  src/Nethermind/Nethermind.Blockchain/BlockTree.cs
  src/Nethermind/Nethermind.Blockchain/Blocks/BlockStore.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
  src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/SyncStatusListTests.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/FastBlockStatus.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/FastBlockStatusList.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/SyncStatusList.cs
Labels: performance
