Repository NethermindEth/nethermind, pull requests merged in 2023-03, with the labels that each got.

#5356 Bring back eth68
  src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
  src/Nethermind/Nethermind.Network/ProtocolsManager.cs
Labels: network

#5350 Add winget package support
  .github/workflows/discord-announcement.yml
  .github/workflows/publish-packages.yml
  .github/workflows/release.yml
  README.md
  scripts/deployment/publish-github.sh
  scripts/deployment/publish-ppa.sh
Labels: devops, release, docs

#5380 Remove unused runtime features
  src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
Labels: security, performance

#5389 Stronger guarantees of state return during failures
  src/Nethermind/Nethermind.Evm/EvmStack.cs
  src/Nethermind/Nethermind.Evm/EvmState.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
Labels: bug

#5403 Remove discord announcement
  .github/workflows/discord-announcement.yml
Labels: devops

#5397 LruCache faster snapshot
  src/Nethermind/Nethermind.Core/Caching/LruCache.cs
  src/Nethermind/Nethermind.Trie/CachingStore.cs
Labels: performance, pleasure to code

#5385 Fix exception in CleanupOldPayloads from concurrent use of List
  src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs
Labels: bug, performance

#5407 In FastHeadersSyncFeed change ConcurrentDictionary to ConcurrentHashSet
  src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/Nethermind.Synchronization.csproj
Labels: performance

#5411 Fix/bad blocks v5
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
  src/Nethermind/Nethermind.Consensus/Producers/BlockProducerBase.cs
  src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
  src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergePluginTests.cs
  src/Nethermind/Nethermind.Merge.AuRa/AuRaPostMergeBlockProducer.cs
  src/Nethermind/Nethermind.Merge.AuRa/AuRaPostMergeBlockProducerFactory.cs
  src/Nethermind/Nethermind.Merge.AuRa/EmptyBlockProductionException.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/BlockTreeTests.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.MockBlockImprovementContextFactory.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.StoringBlockImprovementContextFactory.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.PayloadProduction.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidBlockInterceptorTest.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidHeaderInterceptorTest.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidHeaderSealInterceptorTest.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/MergePluginTests.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/PoSSwitcherTests.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/Synchronization/BeaconHeadersSyncTests.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/Synchronization/PeerRefresherTests.cs
  src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/EmptyBlockProductionException.cs
  src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PostMergeBlockProducer.cs
Labels: bug

#5405 Make TraverseContext readonly and pass via in
  src/Nethermind/Nethermind.Core.Test/BytesTests.cs
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Core/Extensions/SpanExtensions.cs
  src/Nethermind/Nethermind.Trie/PatriciaTree.cs
Labels: performance

#5415 Fix posdao tests - disable filters only if there is priority contract
  src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/InitializeBlockchainAuRa.cs
  src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
  src/Nethermind/Nethermind.TxPool/Filters/BalanceZeroFilter.cs
  src/Nethermind/Nethermind.TxPool/Filters/FeeTooLowFilter.cs
  src/Nethermind/Nethermind.TxPool/TxPool.cs
Labels: bug

#5401 Perf/pool trie store
  src/Nethermind/Directory.Packages.props
  src/Nethermind/Nethermind.Synchronization/Nethermind.Synchronization.csproj
  src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs
Labels: performance

#5421 Switch off DotNetty ResourceLeakDetector
  src/Nethermind/Nethermind.Runner/Program.cs
Labels: performance

#5426 Only clear NetworkNode cache on changes
  src/Nethermind/Nethermind.Network/NetworkStorage.cs
Labels: performance

#5432 Migrate To use BitOperation Class for BinaryOperations
  src/Nethermind/Nethermind.Merkleization/Merkle.cs
Labels: performance

#5433 Reduce state access for TxPool
  src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
  src/Nethermind/Nethermind.TxPool/Collections/TxDistinctSortedPool.cs
  src/Nethermind/Nethermind.TxPool/Filters/DeployedCodeFilter.cs
  src/Nethermind/Nethermind.TxPool/TxPool.cs
Labels: performance

#5457 Reduce TrieNode allocations
  src/Nethermind/Nethermind.Benchmark/Store/PatriciaTreeBenchmarks.cs
  src/Nethermind/Nethermind.Trie.Test/TrieNodeTests.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
Labels: performance, trie, experimental 💣

#5479 Remove unnecessary GC finalization
  src/Nethermind/Nethermind.Consensus.Ethash/EthashCache.cs
  src/Nethermind/Nethermind.Core/FakeBatch.cs
  src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs
  src/Nethermind/Nethermind.Db/SimpleFilePublicKeyDb.cs
Labels: performance

#5492 Handle TaskCancelledException on startup of runner
  src/Nethermind/Nethermind.Runner/Program.cs
Labels: bug

#5402 Reduce VirtualMachine.Execute call stack
  src/Nethermind/Nethermind.Core/LogEntry.cs
  src/Nethermind/Nethermind.Core/TransactionReceipt.cs
  src/Nethermind/Nethermind.Evm.Benchmark/EvmBenchmarks.cs
  src/Nethermind/Nethermind.Evm.Benchmark/MultipleUnsignedOperations.cs
  src/Nethermind/Nethermind.Evm.Benchmark/StaticCallBenchmarks.cs
  src/Nethermind/Nethermind.Evm/ByteArrayExtensions.cs
  src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
  src/Nethermind/Nethermind.Evm/EvmState.cs
  src/Nethermind/Nethermind.Evm/ExecutionEnvironment.cs
  src/Nethermind/Nethermind.Evm/Precompiles/PointEvaluationPrecompile.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Evm/ZeroPaddedSpan.cs
  src/Nethermind/Nethermind.Merkleization/Merkle.cs
Labels: performance

#5505 Fix the jq error in Hive tests results
  .github/workflows/hive-tests.yml
Labels: devops

#5504 New payload sustained low latency
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
  src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
  src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Paris.cs
  src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs
  src/Nethermind/Nethermind.Merge.Plugin/GC/GCKeeper.cs
  src/Nethermind/Nethermind.Merge.Plugin/GC/IGCStrategy.cs
  src/Nethermind/Nethermind.Merge.Plugin/GC/NoGCStrategy.cs
  src/Nethermind/Nethermind.Merge.Plugin/GC/NoSyncGcRegionStrategy.cs
  src/Nethermind/Nethermind.Merge.Plugin/IMergeConfig.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergeConfig.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
Labels: performance
