Repository NethermindEth/nethermind, pull requests merged in 2024-12, with the labels that each got.

#7844 SyncPeerPool to Channels
  src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs
Labels: performance

#7843 Optimize EvmStack
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Evm.Benchmark/EvmStackBenchmarks.cs
  src/Nethermind/Nethermind.Evm.Test/Tracing/DebugTracerTests.cs
  src/Nethermind/Nethermind.Evm/EvmStack.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.State/StateReader.cs
Labels: performance

#7841 Improve event clean up on disconnected peers
  src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/NodeData/NodeDataProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/SnapProtocolHandler.cs
  src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncFeed.cs
Labels: bug

#7847 Reduce objects in ClockCache
  src/Nethermind/Nethermind.Core/Caching/ClockCache.cs
Labels: performance

#7846 CliqueBlockProducer to Channels
  src/Nethermind/Nethermind.Consensus.Clique/CliqueBlockProducer.cs
Labels: performance

#7852 GC: Clear references in ArrayPoolList before returning to pool
  src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs
Labels: performance

#7788 Only accept txs once synced
  src/Nethermind/Nethermind.Blockchain/BlockTreeExtensions.cs
  src/Nethermind/Nethermind.Blockchain/ChainHeadInfoProvider.cs
  src/Nethermind/Nethermind.Consensus/Processing/CensorshipDetector/CensorshipDetector.cs
  src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
  src/Nethermind/Nethermind.Facade/Eth/EthSyncingInfo.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/ParityRpcModuleTests.cs
  src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
  src/Nethermind/Nethermind.TxPool/AcceptTxResult.cs
  src/Nethermind/Nethermind.TxPool/IChainHeadInfoProvider.cs
  src/Nethermind/Nethermind.TxPool/TxPool.cs
Labels: performance

#7787 ParallelUnbalancedWork for efficient unbalanced parallel loops
  src/Nethermind/Nethermind.Benchmark.Runner/Program.cs
  src/Nethermind/Nethermind.Benchmark/Core/ParallelBenchmark.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
  src/Nethermind/Nethermind.Consensus/Processing/RecoverSignature.cs
  src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs
  src/Nethermind/Nethermind.Core/Threading/ParallelUnbalancedWork.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs
  src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/SyncStatusList.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
Labels: performance

#7869 Add Linea
  README.md
Labels: docs

#7790 Use Channels rather than BlockingCollection for block processing
  src/Nethermind/Nethermind.Consensus.Ethash/Ethash.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
  src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
  src/Nethermind/Nethermind.Core/Threading/ThreadExtensions.cs
  src/Nethermind/Nethermind.Evm/Metrics.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
Labels: performance

#7878 [Json RPC] Catch Trie exception on eth_getStorage call
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
Labels: bug, rpc

#7896 Prevent file logging before configuration initialization
  src/Nethermind/Nethermind.Logging.NLog/NLogManager.cs
  src/Nethermind/Nethermind.Runner/Program.cs
Labels: bug

#7845 TrieStore to Channels
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
Labels: performance

#7923 Snap: Extension Rlp value index is 1
  src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs
Labels: bug

#7961 Change ValueRlpStream to be Span based
  src/Nethermind/Nethermind.Serialization.Rlp/ValueRlpStream.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
Labels: performance

#7953 Remove some closure allocations
  src/Nethermind/Nethermind.Core/Crypto/PublicKey.cs
  src/Nethermind/Nethermind.Db/SimpleFilePublicKeyDb.cs
  src/Nethermind/Nethermind.Network.Discovery/DiscoveryManager.cs
  src/Nethermind/Nethermind.Network.Discovery/IDiscoveryManager.cs
  src/Nethermind/Nethermind.Network.Discovery/NettyDiscoveryHandler.cs
  src/Nethermind/Nethermind.Network.Discovery/Serializers/NeighborsMsgSerializer.cs
  src/Nethermind/Nethermind.Network.Test/ProtocolsManagerTests.cs
  src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ProtocolHandlerBase.cs
  src/Nethermind/Nethermind.Network/P2P/Session.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandler.cs
  src/Nethermind/Nethermind.Network/Rlpx/NettyHandshakeHandler.cs
  src/Nethermind/Nethermind.State.Test/StateReaderTests.cs
  src/Nethermind/Nethermind.State/IReadOnlyStateProviderExtensions.cs
  src/Nethermind/Nethermind.TxPool/Filters/DeployedCodeFilter.cs
Labels: performance

#7942 [JsonRPC] Remove `transactionLogIndex` field from eth_getLogs
  src/Nethermind/Nethermind.Facade/Filters/FilterLog.cs
  src/Nethermind/Nethermind.Facade/Filters/FilterManager.cs
  src/Nethermind/Nethermind.Facade/Find/LogFinder.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/LogsSubscription.cs
Labels: rpc, enhancement

#7955 Add GasLimit to NewPayoad log
  src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
Labels: logging

#7972 Share stack pool between threads
  src/Nethermind/Nethermind.Evm/EvmState.cs
  src/Nethermind/Nethermind.Evm/StackPool.cs
Labels: performance

#7983 Reduce parallel prewarming overwork
  src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/SystemTransactionProcessor.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Facade/Simulate/SimulateTransactionProcessor.cs
  src/Nethermind/Nethermind.Optimism/OptimismTransactionProcessor.cs
  src/Nethermind/Nethermind.Taiko/TaikoTransactionProcessor.cs
Labels: performance

#7984 Reuse thread state when prewarming addresses in parallel
  src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
  src/Nethermind/Nethermind.Core/Threading/ParallelUnbalancedWork.cs
Labels: performance
