Repository NethermindEth/nethermind, pull requests merged in 2024-02, with the labels that each got.

#6653 Robustify Parallel Trie Reads
  src/Nethermind/Nethermind.Trie/TrieNode.cs
Labels: bug

#6673 Push proper error message on kestral exceptions
  src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
Labels: rpc, fix

#6607 StackPool's don't need to be concurrent
  src/Nethermind/Nethermind.Evm/EvmState.cs
Labels: performance

#6687 Fix ShaMerkleTree for multithreaded access
  src/Nethermind/Nethermind.Merkleization/ShaMerkleTree.cs
Labels: bug

#6709 Add Cancun hard-fork settings for Gnosis
  src/Nethermind/Chains/gnosis.json
  src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs
  src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs/GnosisSpecProvider.cs
Labels: configuration, gnosis, cancun

#6750 Calculate Tx Hash if fast path not available
  src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
Labels: bug

#6761 Fix silent backgrount task failure.
  src/Nethermind/Nethermind.Consensus/Scheduler/BackgroundTaskScheduler.cs
  src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs
  src/Nethermind/Nethermind.Network.Stats/Model/DisconnectReason.cs
  src/Nethermind/Nethermind.Network.Test/P2P/PacketSenderTests.cs
  src/Nethermind/Nethermind.Network/P2P/Messages/P2PMessage.cs
  src/Nethermind/Nethermind.Network/P2P/PacketSender.cs
  src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ProtocolHandlerBase.cs
  src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/HashesMessage.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/PooledTxsRequestor.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/TransactionsMessage.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Messages/Eth66Message.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V68/Messages/NewPooledTransactionHashesMessage68.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Les/LesProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/NodeData/NodeDataProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/SnapProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/Utils/BackgroundTaskSchedulerWrapper.cs
Labels: bug

#6773 Use state reader for trie visitor
  src/Nethermind/Nethermind.Init/InitializeStateDb.cs
  src/Nethermind/Nethermind.State.Test/StateProviderTests.cs
  src/Nethermind/Nethermind.State.Test/StateReaderTests.cs
  src/Nethermind/Nethermind.State/IWorldStateExtensions.cs
  src/Nethermind/Nethermind.State/StateReaderExtensions.cs
Labels: minor

#6774 Put clique block producer on dispose stack
  src/Nethermind/Nethermind.Consensus.Clique/CliquePlugin.cs
Labels: fix

#6785 Set eth67 and eth68 as default capabilities
  src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
  src/Nethermind/Nethermind.Network.Test/P2P/P2PProtocolHandlerTests.cs
  src/Nethermind/Nethermind.Network.Test/P2P/P2PProtocolInfoProviderTests.cs
  src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs
Labels: network
