Repository NethermindEth/nethermind, pull requests merged in 2024-09, with the labels that each got.

#7375 Only need single stack for stacks
  src/Nethermind/Nethermind.Evm/EvmState.cs
Labels: performance

#7377 Add dual array concat overload
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
Labels: performance

#7380 Disable warning in engine_getBlobsV1
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/EngineRpcCapabilitiesProvider.cs
Labels: engine

#7398 `TxDecoders` folder renaming
  src/Nethermind/Nethermind.Serialization.Rlp/TxDecoders/AccessListTxDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/TxDecoders/BaseTxDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/TxDecoders/BlobTxDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/TxDecoders/EIP1559TxDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/TxDecoders/ITxDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/TxDecoders/LegacyTxDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/TxDecoders/OptimismTxDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/TxDecoders/SignatureBuilder.cs
Labels: fix

#7456 Remove Goerli
  README.md
Labels: docs

#7442 Recheck if empty under lock, early exit
  src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
  src/Nethermind/Nethermind.Consensus/Processing/IBlockCachePreWarmer.cs
  src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
  src/Nethermind/Nethermind.Core/Collections/CollectionExtensions.cs
  src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/TraceRpcModuleTests.cs
  src/Nethermind/Nethermind.State/IWorldState.cs
  src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
  src/Nethermind/Nethermind.State/PreBlockCaches.cs
  src/Nethermind/Nethermind.State/StateProvider.cs
  src/Nethermind/Nethermind.State/WorldState.cs
  src/Nethermind/Nethermind.Trie/PreCachedTrieStore.cs
Labels: performance

#7336 Fast Keccak cache (wait-free and lockless)
  src/Nethermind/Nethermind.Core.Test/KeccakCacheTests.cs
  src/Nethermind/Nethermind.Core/Address.cs
  src/Nethermind/Nethermind.Core/Bloom.cs
  src/Nethermind/Nethermind.Core/Crypto/Hash256.cs
  src/Nethermind/Nethermind.Core/Crypto/KeccakCache.cs
  src/Nethermind/Nethermind.Core/Crypto/PublicKey.cs
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Core/Extensions/SpanExtensions.cs
  src/Nethermind/Nethermind.Core/StorageCell.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
  src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
  src/Nethermind/Nethermind.State/PreBlockCaches.cs
  src/Nethermind/Nethermind.State/StateTree.cs
  src/Nethermind/Nethermind.State/StorageTree.cs
Labels: performance

#7465 Revise the configuration options docs
  src/Nethermind/Nethermind.Config/IBlocksConfig.cs
  src/Nethermind/Nethermind.Consensus/IMiningConfig.cs
  src/Nethermind/Nethermind.Db/IPruningConfig.cs
  src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs
  src/Nethermind/Nethermind.Optimism/IOptimismConfig.cs
Labels: docs

#7450 Refactor and improve DB size generator
  .github/workflows/update-docs.yml
  tools/docgen/ConfigGenerator.cs
  tools/docgen/DBSizeGenerator.cs
  tools/docgen/DocGen.csproj
  tools/docgen/JsonRpcGenerator.cs
  tools/docgen/MetricsGenerator.cs
  tools/docgen/Program.cs
  tools/docgen/Properties/launchSettings.json
  tools/docgen/nuget.config
Labels: docs

#7472 Don't convert tx.Data to array unnecessarily
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
Labels: performance

#7468 Optimize out DaoTransition call
  src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
Labels: performance

#7473 Calculate receipt blooms in parallel
  src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
  src/Nethermind/Nethermind.Core/TransactionReceipt.cs
  src/Nethermind/Nethermind.Evm/Tracing/BlockReceiptsTracer.cs
  src/Nethermind/Nethermind.Optimism/OptimismBlockReceiptTracer.cs
Labels: performance

#7476 Use non-allocating key in more places
  src/Nethermind/Nethermind.TxPool/BlobTxStorage.cs
Labels: performance

#7477 Bump unstable to 1.30.0
  src/Nethermind/Directory.Build.props
Labels: release

#7469 Move txPool work from Processing loop event to txPool thread
  src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
  src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcSocketsClientTests.cs
  src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
  src/Nethermind/Nethermind.TxPool/ITxPool.cs
  src/Nethermind/Nethermind.TxPool/NullTxPool.cs
  src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs
  src/Nethermind/Nethermind.TxPool/TxPool.cs
Labels: performance

#7499 Pin action versions in `codeql.yml`
  .github/workflows/codeql.yml
Labels: devops

#7507 Reduce GC pause from 1sec to 500ms for faster blocks
  src/Nethermind/Nethermind.Merge.Plugin/GC/GCKeeper.cs
Labels: optimism

#7509 Reuse ClassLoggers
  src/Nethermind/Nethermind.Core.Test/NUnitLogManager.cs
  src/Nethermind/Nethermind.Logging.NLog/NLogManager.cs
  src/Nethermind/Nethermind.Logging/ILogManager.cs
  src/Nethermind/Nethermind.Logging/LimboLogs.cs
  src/Nethermind/Nethermind.Logging/NoErrorLimboLogs.cs
  src/Nethermind/Nethermind.Logging/NullLogManager.cs
  src/Nethermind/Nethermind.Logging/OneLoggerLogManager.cs
  src/Nethermind/Nethermind.Logging/SimpleConsoleLogManager.cs
  src/Nethermind/Nethermind.Logging/TestErrorLogManager.cs
  src/Nethermind/Nethermind.Logging/TestLogManager.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
  src/Nethermind/Nethermind.Synchronization.Test/SyncReportTest.cs
Labels: optimism

#7512 Increase object pool sizes in prewarmer
  src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
Labels: performance
