Repository NethermindEth/nethermind, pull requests merged in 2024-01, with the labels that each got.

#6446 Fix `BlobGasUsed` and `ExcessBlobGas` in Cancun genesis
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecGenesisJson.cs
Labels: cancun

#6452 Use the empty account cache as cache
  src/Nethermind/Nethermind.State/StateProvider.cs
Labels: performance

#6496 Fix NuGet package path
  .github/workflows/publish-nuget.yml
Labels: release

#6528 Feature: Exposing Prometheus metrics to user-defined interface
  src/Nethermind/Nethermind.Monitoring/Config/IMetricsConfig.cs
  src/Nethermind/Nethermind.Monitoring/Config/MetricsConfig.cs
  src/Nethermind/Nethermind.Monitoring/MonitoringService.cs
Labels: metrics

#6534 Reduce allocations in StorageRangesMessageSerializer
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/StorageRangesMessageSerializer.cs
  src/Nethermind/Nethermind.State/Snap/PathWithStorageSlot.cs
Labels: performance

#6536 Propagate pooled arrays to RlpStream
  src/Nethermind/Nethermind.AccountAbstraction/Data/UserOperationDecoder.cs
  src/Nethermind/Nethermind.Blockchain.Test/Receipts/KeccaksIteratorTests.cs
  src/Nethermind/Nethermind.Consensus.AuRa/Validators/PendingValidatorsDecoder.cs
  src/Nethermind/Nethermind.Consensus.AuRa/Validators/ValidatorInfoDecoder.cs
  src/Nethermind/Nethermind.Consensus.Clique/CliqueBlockProducer.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockExtensions.cs
  src/Nethermind/Nethermind.Consensus/Validators/BlockValidator.cs
  src/Nethermind/Nethermind.Core.Test/Builders/BlockBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Builders/BlockTreeBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Encoding/AccessListDecoderTests.cs
  src/Nethermind/Nethermind.Core.Test/Encoding/BlockInfoDecoderTests.cs
  src/Nethermind/Nethermind.Core.Test/Encoding/TxDecoderTests.cs
  src/Nethermind/Nethermind.Core.Test/RlpTests.cs
  src/Nethermind/Nethermind.Core/Buffers/CappedArray.cs
  src/Nethermind/Nethermind.Core/Buffers/ICappedArrayPool.cs
  src/Nethermind/Nethermind.Core/KeyValueStoreExtensions.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugBridge.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Proof/ProofRpcModule.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayload.cs
  src/Nethermind/Nethermind.Merge.Plugin/Synchronization/PivotUpdator.cs
  src/Nethermind/Nethermind.Network.Enr/NodeRecord.cs
  src/Nethermind/Nethermind.Network.Enr/NodeRecordSigner.cs
  src/Nethermind/Nethermind.Network/NetworkNodeDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/AccountDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/BlockDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/ByteArrayExtensions.cs
  src/Nethermind/Nethermind.Serialization.Rlp/CompactReceiptStorageDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/HeaderDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/LogEntryDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/ReceiptMessageDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/ReceiptStorageDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpDecoderExtensions.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
  src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/WithdrawalDecoder.cs
  src/Nethermind/Nethermind.State/Proofs/ReceiptTrie.cs
  src/Nethermind/Nethermind.State/Proofs/TxTrie.cs
  src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloadContext.cs
  src/Nethermind/Nethermind.Synchronization/FastSync/DetailedProgress.cs
  src/Nethermind/Nethermind.Synchronization/LesSync/CanonicalHashTrie.cs
  src/Nethermind/Nethermind.Trie.Test/TrackingCappedArrayPoolTests.cs
  src/Nethermind/Nethermind.Trie/PatriciaTree.cs
  src/Nethermind/Nethermind.Trie/TrackingCappedArrayPool.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
  src/Nethermind/Nethermind.Trie/TrieNodeFactory.cs
  src/Nethermind/Nethermind.TxPool/LightTxDecoder.cs
Labels: performance

#6532 Skip adding Mvc controllers on start-up
  src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
Labels: performance

#6541 Reduce readonly CALL allocations by 64 bytes
  src/Nethermind/Nethermind.Trie/PatriciaTree.cs
Labels: performance

#6540 Improve JumpDestinationAnalyzer; run in parallel
  src/Nethermind/Nethermind.Evm/CodeAnalysis/JumpDestinationAnalyzer.cs
  src/Nethermind/Nethermind.Evm/EvmAccessViolationException.cs
  src/Nethermind/Nethermind.Evm/InvalidJumpDestinationException.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
Labels: performance, pleasure to code

#6533 Remove contention from KeccakHash during Sync
  src/Nethermind/Nethermind.Core/Crypto/KeccakHash.cs
Labels: performance

#6457 Add Cancun hard-fork settings for Chiado testnet
  src/Nethermind/Chains/chiado.json
  src/Nethermind/Chains/goerli.json
  src/Nethermind/Nethermind.Blockchain/BeaconBlockRoot/BeaconBlockRootHandler.cs
  src/Nethermind/Nethermind.Core/Eip4788Constants.cs
  src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs
  src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs
  src/Nethermind/Nethermind.Specs/ChiadoSpecProvider.cs
  src/Nethermind/Nethermind.Specs/Forks/16_Cancun.cs
Labels: configuration, gnosis, cancun

#6527 [Fix]{Config] old default barrier being ignoreed in clients upgraded to new versions but were initailly synced with older versions (1.19.3 and below))
  src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/BodiesSyncFeedTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/ReceiptsSyncFeedTests.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/BarrierSyncFeed.cs
Labels: bug

#6515 [Fix] EthSyncing showing Syncing even when node is fully synced up to old default barrier
  src/Nethermind/Nethermind.AccountAbstraction.Test/UserOperationSubscribeTests.cs
  src/Nethermind/Nethermind.Facade.Test/Eth/EthSyncingInfoTests.cs
  src/Nethermind/Nethermind.Facade/Eth/EthSyncingInfo.cs
  src/Nethermind/Nethermind.HealthChecks.Test/NodeHealthServiceTests.cs
  src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
  src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcBlockchain.cs
  src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergeEngineModuleTests.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
Labels: bug

#6551 Optimize GMP data import
  src/Nethermind/Nethermind.Evm/Precompiles/ModExpPrecompile.cs
Labels: performance

#6553 Fix solution files
  src/Nethermind/Benchmarks.sln
  src/Nethermind/EthereumTests.sln
Labels: bug

#6580 Increase Trie robustness for multi-readers
  src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
  src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs
  src/Nethermind/Nethermind.Trie/PatriciaTree.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
Labels: bug

#6584 Trie RlpStreams as structs
  src/Nethermind/Nethermind.Serialization.Rlp/ByteArrayExtensions.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpFactory.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
  src/Nethermind/Nethermind.Serialization.Rlp/ValueRlpStream.cs
  src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
Labels: performance

#6587 Add colors to logging for MGas
  src/Nethermind/Nethermind.Blockchain/Metrics.cs
  src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
Labels: logging

#6594 Disconnect timed out connects
  src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs
Labels: bug

#6608 Ignore Span wrapping properties for Json serialization
  src/Nethermind/Nethermind.Core/Crypto/Signature.cs
Labels: bug

#6618 Revise PPA packaging
  .github/workflows/publish-packages.yml
  scripts/deployment/debian/compat
  scripts/deployment/debian/control
  scripts/deployment/debian/postinst
  scripts/deployment/debian/prerm
  scripts/deployment/ppa/debian/control
  scripts/deployment/ppa/debian/copyright
  scripts/deployment/ppa/debian/postinst
  scripts/deployment/ppa/debian/postrm
  scripts/deployment/ppa/debian/rules
  scripts/deployment/ppa/debian/source/format
  scripts/execution.sh
Labels: bug, devops

#6623 Don't capture tx in ShouldGossipTransaction closure
  src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandlerTests.cs
  src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandlerTests.cs
  src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandlerTests.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandler.cs
  src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/SyncedTxGossipPolicyTests.cs
  src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncedTxGossipPolicy.cs
  src/Nethermind/Nethermind.TxPool/ITxGossipPolicy.cs
Labels: performance

#6630 VerifyCapacity under lock
  src/Nethermind/Nethermind.TxPool/Collections/TxDistinctSortedPool.cs
  src/Nethermind/Nethermind.TxPool/TxPool.cs
Labels: bug

#6634 Revise release workflow
  .github/workflows/publish-nuget.yml
  .github/workflows/publish-packages.yml
  scripts/deployment/build-cli.sh
  scripts/deployment/build-runner.sh
  scripts/deployment/publish-downloads.sh
  scripts/deployment/publish-github.sh
Labels: bug, devops

#6621 Revise docs generation
  .github/workflows/update-docs.yml
  src/Nethermind/Nethermind.Api/IInitConfig.cs
  src/Nethermind/Nethermind.Monitoring/Config/IMetricsConfig.cs
  tools/docgen/JsonRpcGenerator.cs
Labels: bug, docs

#6636 Exclude Tx Hashes when serving Blocks & apply network back pressure
  src/Nethermind/Nethermind.AccountAbstraction/Network/UserOperationsMessageSerializer.cs
  src/Nethermind/Nethermind.Blockchain.Test/Blocks/BlockStoreTests.cs
  src/Nethermind/Nethermind.Blockchain/BlockTree.cs
  src/Nethermind/Nethermind.Blockchain/BlockTreeMethodOptions.cs
  src/Nethermind/Nethermind.Blockchain/Blocks/BlockStore.cs
  src/Nethermind/Nethermind.Blockchain/Blocks/IBlockStore.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
  src/Nethermind/Nethermind.Merge.Plugin/IMergeConfig.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergeConfig.cs
  src/Nethermind/Nethermind.Network.Test/P2P/PacketSenderTests.cs
  src/Nethermind/Nethermind.Network/P2P/Messages/AddCapabilityMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Messages/DisconnectMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Messages/HelloMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/PacketSender.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/HashesMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/BlockBodiesMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/BlockHeadersMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/GetBlockBodiesMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/GetBlockHeadersMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/NewBlockHashesMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/NewBlockMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/TransactionsMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V63/Messages/NodeDataMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V63/Messages/ReceiptsMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Messages/Eth66MessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V68/Messages/NewPooledTransactionHashesMessageSerializer68.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Les/Messages/BlockHeadersMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Les/Messages/GetBlockHeadersMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/NodeData/Messages/NodeDataMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/AccountRangeMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/ByteCodesMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/GetTrieNodesMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/SnapSerializerBase.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/StorageRangesMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/TrieNodesMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Wit/Messages/BlockWitnessHashesMessageSerializer.cs
  src/Nethermind/Nethermind.Network/Rlpx/Handshake/AckEip8MessageSerializer.cs
  src/Nethermind/Nethermind.Network/Rlpx/Handshake/AuthEip8MessageSerializer.cs
  src/Nethermind/Nethermind.Network/Rlpx/Handshake/AuthMessageSerializer.cs
  src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs
  src/Nethermind/Nethermind.Network/Rlpx/ZeroFrameEncoder.cs
  src/Nethermind/Nethermind.Network/Rlpx/ZeroPacketSplitter.cs
  src/Nethermind/Nethermind.Network/Rlpx/ZeroSnappyEncoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/BlockDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/KeyValueStoreRlpExtensions.cs
  src/Nethermind/Nethermind.Serialization.Rlp/NettyRlpStream.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpBehaviors.cs
  src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs
  src/Nethermind/Nethermind.Synchronization.Test/SyncServerTests.cs
  src/Nethermind/Nethermind.Synchronization/SyncServer.cs
Labels: bug, performance
