Repository NethermindEth/nethermind, pull requests merged in 2024-06, with the labels that each got.

#7123 Update Fast Sync configuration in Nethermind repository
  src/Nethermind/Nethermind.Runner/configs/chiado.cfg
  src/Nethermind/Nethermind.Runner/configs/energyweb.cfg
  src/Nethermind/Nethermind.Runner/configs/exosama.cfg
  src/Nethermind/Nethermind.Runner/configs/gnosis.cfg
  src/Nethermind/Nethermind.Runner/configs/joc-mainnet.cfg
  src/Nethermind/Nethermind.Runner/configs/joc-testnet.cfg
  src/Nethermind/Nethermind.Runner/configs/mainnet.cfg
  src/Nethermind/Nethermind.Runner/configs/sepolia.cfg
  src/Nethermind/Nethermind.Runner/configs/volta.cfg
Labels: configs

#7124 Replace Bouncy Castle package
  src/Nethermind/Directory.Packages.props
  src/Nethermind/Nethermind.Crypto/AesEngineX86Intrinsic.cs
  src/Nethermind/Nethermind.Crypto/EciesCipher.cs
  src/Nethermind/Nethermind.Crypto/EthereumIesEngine.cs
  src/Nethermind/Nethermind.Crypto/Nethermind.Crypto.csproj
  src/Nethermind/Nethermind.Network/Rlpx/FrameCipher.cs
  src/Nethermind/Nethermind.Network/Rlpx/FrameMacProcessor.cs
Labels: cryptography

#7154 Update Fast Sync configuration in Nethermind repository
  src/Nethermind/Nethermind.Runner/configs/chiado.cfg
  src/Nethermind/Nethermind.Runner/configs/energyweb.cfg
  src/Nethermind/Nethermind.Runner/configs/exosama.cfg
  src/Nethermind/Nethermind.Runner/configs/gnosis.cfg
  src/Nethermind/Nethermind.Runner/configs/joc-mainnet.cfg
  src/Nethermind/Nethermind.Runner/configs/joc-testnet.cfg
  src/Nethermind/Nethermind.Runner/configs/mainnet.cfg
  src/Nethermind/Nethermind.Runner/configs/sepolia.cfg
  src/Nethermind/Nethermind.Runner/configs/volta.cfg
Labels: configs

#7177 Replace `JwtSecurityToken` with `JsonWebToken`
  src/Nethermind/Nethermind.Analytics/AnalyticsWebSocketsModule.cs
  src/Nethermind/Nethermind.Core/Authentication/IRpcAuthentication.cs
  src/Nethermind/Nethermind.Core/Authentication/JwtAuthentication.cs
  src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcWebSocketsModule.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/JwtTest.cs
  src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
  src/Nethermind/Nethermind.Sockets/Extensions.cs
  src/Nethermind/Nethermind.Sockets/IWebSocketsModule.cs
Labels: performance

#7207 Revise JWT authentication check
  src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcWebSocketsModule.cs
  src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
Labels: bug

#7191 ci: remove repository dispatch token usage
  .github/workflows/hive-consensus-tests.yml
  .github/workflows/publish-packages.yml
  .github/workflows/release.yml
  .github/workflows/run-a-single-node-from-branch.yml
  .github/workflows/update-config-files.yml
  .github/workflows/update-dappnode-package.yml
  .github/workflows/update-docs.yml
Labels: devops

#7211 fix: remove old dappnode workflows
  .github/workflows/release.yml
  .github/workflows/update-dappnode-package.yml
Labels: devops
