Repository NethermindEth/nethermind, pull requests merged in 2024-03, with the labels that each got.

#6795 Leaf value collector
  src/Nethermind/Nethermind.Core/Collections/IOwnedReadOnlyList.cs
  src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Snap/Messages/StorageRangesMessageSerializerTests.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/StorageRangeMessage.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/StorageRangesMessageSerializer.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/SnapProtocolHandler.cs
  src/Nethermind/Nethermind.Serialization.Rlp/AccountDecoder.cs
  src/Nethermind/Nethermind.State.Test/SnapSync/RecreateStateFromAccountRangesTests.cs
  src/Nethermind/Nethermind.State.Test/SnapSync/RecreateStateFromStorageRangesTests.cs
  src/Nethermind/Nethermind.State/Snap/SlotsAndProofs.cs
  src/Nethermind/Nethermind.Synchronization.Test/RangeQueryVisitorTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SnapSync/ProgressTrackerTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SnapSync/RecreateStateFromAccountRangesTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SnapSync/RecreateStateFromStorageRangesTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SnapSync/SnapServerTest.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/AccountCollector.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/ISnapServer.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/PathWithStorageCollector.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/SnapServer.cs
  src/Nethermind/Nethermind.Synchronization/Synchronizer.cs
  src/Nethermind/Nethermind.Trie/RangeQueryVisitor.cs
Labels: performance

#6806 Allow serving snap without having snap sync enabled
  src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
Labels: minor

#6804 Revise validation errors
  src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs
  src/Nethermind/Nethermind.Blockchain.Test/Validators/BlockValidatorTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/Validators/HeaderValidatorTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/Validators/TestBlockValidator.cs
  src/Nethermind/Nethermind.Blockchain.Test/Validators/TestTransactionValidator.cs
  src/Nethermind/Nethermind.Blockchain.Test/Validators/TxValidatorTests.cs
  src/Nethermind/Nethermind.Blockchain/InvalidBlockException.cs
  src/Nethermind/Nethermind.Consensus.AuRa/AuRaHeaderValidator.cs
  src/Nethermind/Nethermind.Consensus/Messages/BlockErrorMessages.cs
  src/Nethermind/Nethermind.Consensus/Messages/TxErrorMessages.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockRemovedEventArgs.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
  src/Nethermind/Nethermind.Consensus/Processing/IBlockProcessingQueue.cs
  src/Nethermind/Nethermind.Consensus/Validators/AlwaysValid.cs
  src/Nethermind/Nethermind.Consensus/Validators/BlockValidator.cs
  src/Nethermind/Nethermind.Consensus/Validators/Extensions.cs
  src/Nethermind/Nethermind.Consensus/Validators/HeaderValidator.cs
  src/Nethermind/Nethermind.Consensus/Validators/IBlockValidator.cs
  src/Nethermind/Nethermind.Consensus/Validators/IHeaderValidator.cs
  src/Nethermind/Nethermind.Consensus/Validators/NeverValidBlockValidator.cs
  src/Nethermind/Nethermind.Consensus/Validators/TxValidator.cs
  src/Nethermind/Nethermind.Consensus/Validators/UnclesValidator.cs
  src/Nethermind/Nethermind.Core.Test/Builders/BlockValidatorBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Builders/TransactionValidatorBuilder.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.Hive/HiveRunner.cs
  src/Nethermind/Nethermind.Logging/ILogger.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidBlockInterceptorTest.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidHeaderInterceptorTest.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/NewPayloadV1Result.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/InvalidChainTracker/InvalidBlockInterceptor.cs
  src/Nethermind/Nethermind.Merge.Plugin/InvalidChainTracker/InvalidHeaderInterceptor.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergeHeaderValidator.cs
  src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloader.cs
  src/Nethermind/Nethermind.Mev/Source/BundlePool.cs
  src/Nethermind/Nethermind.Optimism/OptimismHeaderValidator.cs
  src/Nethermind/Nethermind.Optimism/OptimismTxValidator.cs
  src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
  src/Nethermind/Nethermind.Synchronization/SyncServer.cs
  src/Nethermind/Nethermind.TxPool/Filters/MalformedTxFilter.cs
  src/Nethermind/Nethermind.TxPool/ITxValidator.cs
  tools/HiveConsensusWorkflowGenerator/Program.cs
  tools/SendBlobs/SetupCli.cs
  tools/docgen/ConfigGenerator.cs
Labels: engine, consensus

#6824 Fix arraylength check on null parameters
  src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs
Labels: bug

#6825 Support AddressAsKey Json Serialization
  src/Nethermind/Nethermind.JsonRpc.Test/Data/DictionaryConverterTests.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Data/SerializationTestBase.cs
  src/Nethermind/Nethermind.Serialization.Json/DictionaryAddressKey.cs
Labels: bug

#6882 Update Fast Sync configuration in Nethermind repository
  src/Nethermind/Nethermind.Runner/configs/chiado.cfg
  src/Nethermind/Nethermind.Runner/configs/energyweb.cfg
  src/Nethermind/Nethermind.Runner/configs/exosama.cfg
  src/Nethermind/Nethermind.Runner/configs/gnosis.cfg
  src/Nethermind/Nethermind.Runner/configs/joc-mainnet.cfg
  src/Nethermind/Nethermind.Runner/configs/joc-testnet.cfg
  src/Nethermind/Nethermind.Runner/configs/mainnet.cfg
  src/Nethermind/Nethermind.Runner/configs/sepolia.cfg
  src/Nethermind/Nethermind.Runner/configs/volta.cfg
Labels: configs
