Repository NethermindEth/nethermind, pull requests merged in 2024-11, with the labels that each got.

#7714 Fix IPC data handling
  src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcSocketsClientTests.cs
  src/Nethermind/Nethermind.Runner/Properties/launchSettings.json
  src/Nethermind/Nethermind.Sockets/IpcSocketMessageStream.cs
Labels: bug, ipc

#7700 Add Taiko and revise the list
  README.md
Labels: docs

#7532 Migrate to .NET 9
  .github/workflows/build-solutions.yml
  .github/workflows/nethermind-tests.yml
  Dockerfile
  Dockerfile.chiseled
  Dockerfile.diag
  global.json
  src/Nethermind/Directory.Build.props
  src/Nethermind/Directory.Packages.props
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Crypto/KzgPolynomialCommitments.cs
  src/Nethermind/Nethermind.Crypto/kzg_trusted_setup.txt
  src/Nethermind/Nethermind.ExternalSigner.Plugin/Nethermind.ExternalSigner.Plugin.csproj
  src/Nethermind/Nethermind.Facade.Test/BlockchainBridgeTests.cs
  src/Nethermind/Nethermind.JsonRpc/Nethermind.JsonRpc.csproj
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.RelayBuilder.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
  src/Nethermind/Nethermind.Network.Discovery/NettyDiscoveryHandler.cs
  src/Nethermind/Nethermind.Network.Stats/NodeStatsLight.cs
  src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs
  src/Nethermind/Nethermind.Runner/Dockerfile
  src/Nethermind/Nethermind.Runner/Properties/launchSettings.json
  src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
  tools/Directory.Build.props
  tools/DocGen/DocGen.csproj
  tools/Evm/Evm.csproj
  tools/HiveCompare/HiveCompare.csproj
  tools/HiveCompare/HiveCompare.sln
  tools/HiveCompare/Models/HiveTestResult.cs
  tools/HiveCompare/Program.cs
  tools/HiveConsensusWorkflowGenerator/HiveConsensusWorkflowGenerator.csproj
  tools/HiveConsensusWorkflowGenerator/HiveConsensusWorkflowGenerator.sln
  tools/Nethermind.Tools.Kute/Nethermind.Tools.Kute.csproj
  tools/Nethermind.Tools.Kute/Nethermind.Tools.Kute.sln
  tools/SendBlobs/SendBlobs.csproj
  tools/TxParser/TxParser.csproj
  tools/TxParser/TxParser.sln
Labels: .net

#7694 Unify environment variables
  src/Nethermind/Nethermind.Config.Test/ConfigProvider_FindIncorrectSettings_Tests.cs
  src/Nethermind/Nethermind.Config/EnvConfigSource.cs
  src/Nethermind/Nethermind.Config/INoCategoryConfig.cs
  src/Nethermind/Nethermind.Config/NoCategoryConfig.cs
  src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcUrlCollectionTests.cs
  src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs
  src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs
  src/Nethermind/Nethermind.JsonRpc/JsonRpcUrlCollection.cs
  src/Nethermind/Nethermind.Monitoring/Config/IMetricsConfig.cs
  src/Nethermind/Nethermind.Monitoring/Config/MetricsConfig.cs
  src/Nethermind/Nethermind.Monitoring/MonitoringService.cs
  src/Nethermind/Nethermind.Network/IP/EnvironmentVariableIPSource.cs
  src/Nethermind/Nethermind.Network/IPResolver.cs
  src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs
  src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
Labels: refactoring

#7782 Switch off Response Compression for loopback
  src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
Labels: performance

#7730 Add taiko setup to sync chains workflow
  .github/workflows/sync-supported-chains.yml
  scripts/waitForSync.py
  scripts/workflow_config/sync_testnets_matrix.json
Labels: devops
