Repository NethermindEth/nethermind, pull requests merged in 2025-04, with the labels that each got.

#8437 Secp256r1 precompile: switch to BoringSSL
  src/Nethermind/Benchmarks.slnx
  src/Nethermind/Directory.Packages.props
  src/Nethermind/Nethermind.Evm.Benchmark/StaticCallBenchmarks.cs
  src/Nethermind/Nethermind.Evm.Test/Secp256r1PrecompileTests.cs
  src/Nethermind/Nethermind.Evm/Nethermind.Evm.csproj
  src/Nethermind/Nethermind.Evm/Precompiles/Secp256r1Precompile.cs
  src/Nethermind/Nethermind.Precompiles.Benchmark/PrecompileBenchmarkBase.cs
Labels: performance is good

#8423 Correct timestamp in `eth_simulateV1`
  src/Nethermind/Nethermind.Api/NethermindApi.cs
  src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
  src/Nethermind/Nethermind.Facade.Test/BlockchainBridgeTests.cs
  src/Nethermind/Nethermind.Facade/Simulate/ISimulateTransactionProcessorFactory.cs
  src/Nethermind/Nethermind.Facade/Simulate/SimulateBridgeHelper.cs
  src/Nethermind/Nethermind.Facade/Simulate/SimulateReadOnlyBlocksProcessingEnv.cs
  src/Nethermind/Nethermind.Facade/Simulate/SimulateReadOnlyBlocksProcessingEnvFactory.cs
  src/Nethermind/Nethermind.Facade/Simulate/SimulateTransactionProcessor.cs
  src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/Simulate/EthSimulateTestsHiveBase.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcBlockchain.cs
  src/Nethermind/Nethermind.Optimism/InitializeBlockchainOptimism.cs
  src/Nethermind/Nethermind.Optimism/OptimismReceiptMessageDecoder.cs
  src/Nethermind/Nethermind.Optimism/OptimismTransactionProcessor.cs
  src/Nethermind/Nethermind.Optimism/SimulateOptimismTransactionProcessor.cs
Labels: bug fix + reliability

#8456 Differentiate Pruning metrics
  src/Nethermind/Nethermind.Trie/Pruning/TrieStoreDirtyNodesCache.cs
Labels: minor, bug fix + reliability

#8457 Remove branch from Purning Metrics
  src/Nethermind/Nethermind.Trie/Pruning/Metrics.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStoreDirtyNodesCache.cs
Labels: refactoring, performance is good, minor

#8117 Fix bump up version workflow
  .github/workflows/bump-version.yml
Labels: devops

#8476 Fix broken Engine API documentation link in error message
  src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
Labels: docs, logging, bug fix + reliability

#8477 Use ArgumentNullException.ThrowIfNull
  src/Nethermind/Nethermind.Era1/EraPathUtils.cs
  src/Nethermind/Nethermind.Era1/EraReader.cs
  src/Nethermind/Nethermind.Hive/HivePlugin.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.BlockProducer.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
  src/Nethermind/Nethermind.Shutter/ShutterPlugin.cs
  src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
Labels: refactoring, performance is good

#8474 Perf/More accurate request limit.
  src/Nethermind/Nethermind.Core.Test/RequestSizer/LatencyAndMessageSizeBasedRequestSizerTests.cs
  src/Nethermind/Nethermind.Core/Collections/SlicedReadOnlyList.cs
  src/Nethermind/Nethermind.Core/RequestSizer/LatencyAndMessageSizeBasedRequestSizer.cs
  src/Nethermind/Nethermind.Core/RequestSizer/LatencyBasedRequestSizer.cs
  src/Nethermind/Nethermind.Network.Stats/INodeStats.cs
  src/Nethermind/Nethermind.Network.Stats/INodeStatsManager.cs
  src/Nethermind/Nethermind.Network.Stats/NodeStatsLight.cs
  src/Nethermind/Nethermind.Network.Test/NodeStatsTests.cs
  src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandlerTests.cs
  src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandlerTests.cs
  src/Nethermind/Nethermind.Network.Test/SnapProtocolHandlerTests.cs
  src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs
  src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroProtocolHandlerBase.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandler.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/SnapProtocolHandler.cs
  src/Nethermind/Nethermind.Serialization.Rlp/OwnedBlockBodies.cs
  src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/BodiesSyncFeedTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/FastHeadersSyncTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/SyncDispatcherTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/ReceiptSyncFeedTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SyncPeerPoolTests.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/Peers/ISyncPeerPool.cs
  src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs
Labels: performance is good

#8465 Refactor/Move some TestBlockchain code to DI.
  src/Nethermind/Nethermind.AuRa.Test/Contract/TestContractBlockchain.cs
  src/Nethermind/Nethermind.AuRa.Test/Contract/TxPriorityContractTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/BlockchainProcessorTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPruningDiskTest.cs
  src/Nethermind/Nethermind.Core.Test/Blockchain/BasicTestBlockchain.cs
  src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
  src/Nethermind/Nethermind.Core.Test/Modules/BlockProcessingModule.cs
  src/Nethermind/Nethermind.Core.Test/Modules/BlockTreeModule.cs
  src/Nethermind/Nethermind.Core.Test/Modules/MergeModule.cs
  src/Nethermind/Nethermind.Core.Test/Modules/PseudoNethermindModule.cs
  src/Nethermind/Nethermind.Core.Test/Modules/WorldStateModule.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/DebugRpcModuleTests.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.EthCall.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/Simulate/EthSimulateTestsHiveBase.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcBlockchain.cs
  src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergeEngineModuleTests.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/BaseEngineModuleTests.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs
  src/Nethermind/Nethermind.Shutter.Test/ShutterTestBlockchain.cs
  src/Nethermind/Nethermind.Specs.Test/OverridableSpecProvider.cs
Labels: refactoring, testing

#8478 Update chain sizes test
  src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs
Labels: configuration, testing

#8481 Skip block build if no new tx have been added
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.PayloadProduction.cs
  src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs
  src/Nethermind/Nethermind.TxPool/Metrics.cs
  src/Nethermind/Nethermind.TxPool/TxPool.cs
Labels: performance is good

#8483 Add timeout to node filter
  src/Nethermind/Nethermind.Network.Discovery.Test/NodeLifecycleManagerTests.cs
  src/Nethermind/Nethermind.Network.Discovery/DiscoveryManager.cs
  src/Nethermind/Nethermind.Network.Discovery/IDiscoveryManager.cs
  src/Nethermind/Nethermind.Network.Discovery/NodeFilter.cs
Labels: refactoring, bug fix + reliability

#8492 Include version number in default extra data
  src/Nethermind/Nethermind.Config/BlocksConfig.cs
  src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs
  src/Nethermind/Nethermind.Runner/Program.cs
Labels: enhancement, bug fix + reliability

#8494 Fix FCU result in simulated block production scenarios
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs
Labels: bug fix + reliability

#8497 Dial back JsonRpc log spam
  src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs
Labels: performance is good, logging

#8499 Don't include too much version in extradata
  src/Nethermind/Nethermind.Config/BlocksConfig.cs
  src/Nethermind/Nethermind.Init/Steps/MigrateConfigs.cs
  src/Nethermind/Nethermind.Runner/Program.cs
Labels: bug fix + reliability

#8505 Isolated commit and hash benchmark
  src/Nethermind/Nethermind.Benchmark/Store/PatriciaTreeBenchmarks.cs
Labels: minor

#8498 Don't catch all exceptions on ExecutionPayload.TryGetBlock
  src/Nethermind/Nethermind.Flashbots/Data/BuilderBlockValidationRequest.cs
  src/Nethermind/Nethermind.Flashbots/Handlers/ValidateBuilderSubmissionHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/BaseEngineModuleTests.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.HelperFunctions.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.PayloadProduction.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Synchronization.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V4.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayload.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayloadV3.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/IExecutionPayloadParams.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
  src/Nethermind/Nethermind.Optimism/CL/P2P/P2PBlockValidator.cs
  src/Nethermind/Nethermind.Shutter.Test/ShutterIntegrationTests.cs
  src/Nethermind/Nethermind.Taiko/TaikoExecutionPayload.cs
Labels: bug fix + reliability

#8512 Prefer mev reward tx value when calculating mev
  src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
  src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs
Labels: logging, bug fix + reliability

#8510 Feature/era configurable import blocks buffer
  src/Nethermind/Nethermind.Era.Test/EraImporterTest.cs
  src/Nethermind/Nethermind.Era.Test/EraPathUtilsTests.cs
  src/Nethermind/Nethermind.Era1/EraConfig.cs
  src/Nethermind/Nethermind.Era1/EraImporter.cs
  src/Nethermind/Nethermind.Era1/EraReader.cs
  src/Nethermind/Nethermind.Era1/EraStore.cs
  src/Nethermind/Nethermind.Era1/EraStoreFactory.cs
  src/Nethermind/Nethermind.Era1/IEraConfig.cs
Labels: enhancement, bug fix + reliability

#8511 Cleanup/Remove InitializeNodeStats
  src/Nethermind/Nethermind.Api/IApiWithNetwork.cs
  src/Nethermind/Nethermind.Api/NethermindApi.cs
  src/Nethermind/Nethermind.Core.Test/Modules/PseudoNethermindModule.cs
  src/Nethermind/Nethermind.Core.Test/Modules/PsudoNetworkModule.cs
  src/Nethermind/Nethermind.Init/Modules/BuiltInStepsModule.cs
  src/Nethermind/Nethermind.Init/Modules/NethermindModule.cs
  src/Nethermind/Nethermind.Init/Modules/NetworkModule.cs
  src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
  src/Nethermind/Nethermind.Init/Steps/InitializeNodeStats.cs
  src/Nethermind/Nethermind.Runner.Test/Ethereum/ContextWithMocks.cs
Labels: refactoring

#8523 Limit time any single block can be produced for
  src/Nethermind/Nethermind.Config/BlocksConfig.cs
  src/Nethermind/Nethermind.Config/IBlocksConfig.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
  src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs
Labels: bug fix + reliability

#8495 Add metrics for `engine_getBlobsV1` full and partial responses
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetBlobsHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/Metrics.cs
Labels: metrics

#8500 Added gnosis pectra support
  src/Nethermind/Chains/gnosis.json
  src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs
  src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs/GnosisSpecProvider.cs
Labels: enhancement, consensus, [Pri] Blocker, BREAKING

#8527 CodeDB writes in a batch
  src/Nethermind/Nethermind.Blockchain.Test/ReorgTests.cs
  src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockProcessor.cs
  src/Nethermind/Nethermind.Consensus.AuRa/ContractRewriter.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
  src/Nethermind/Nethermind.Consensus/Processing/IBlockchainProcessor.cs
  src/Nethermind/Nethermind.Consensus/Processing/OneTimeProcessor.cs
  src/Nethermind/Nethermind.Consensus/Processing/ReadOnlyChainProcessingEnv.cs
  src/Nethermind/Nethermind.Core/Crypto/Hash256.cs
  src/Nethermind/Nethermind.Core/Crypto/Hash256AsKeyComparer.cs
  src/Nethermind/Nethermind.Core/Extensions/CancellationTokenExtensions.cs
  src/Nethermind/Nethermind.Evm.Benchmark/EvmBenchmarks.cs
  src/Nethermind/Nethermind.Evm.Benchmark/MultipleUnsignedOperations.cs
  src/Nethermind/Nethermind.Evm.Benchmark/StaticCallBenchmarks.cs
  src/Nethermind/Nethermind.Init/PruningTrieStateFactory.cs
  src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Trace/ParityStyleTracerTests.cs
  src/Nethermind/Nethermind.Runner/configs/mainnet.json
  src/Nethermind/Nethermind.State/Healing/HealingWorldState.cs
  src/Nethermind/Nethermind.State/IWorldStateManager.cs
  src/Nethermind/Nethermind.State/StateProvider.cs
  src/Nethermind/Nethermind.State/WorldState.cs
  src/Nethermind/Nethermind.State/WorldStateManager.cs
Labels: performance is good

#8521 EIP-4444: Add RPC errors for pruned blocks. Take 2
  src/Nethermind/Nethermind.Blockchain/BlockTree.cs
  src/Nethermind/Nethermind.Blockchain/BlockTreeOverlay.cs
  src/Nethermind/Nethermind.Blockchain/Find/IBlockFinder.cs
  src/Nethermind/Nethermind.Blockchain/ReadOnlyBlockTree.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcBlockchain.cs
  src/Nethermind/Nethermind.JsonRpc/ErrorCodes.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/BlockFinderExtensions.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
Labels: rpc, eip-4444

#8502 Mainnet Pectra config
  src/Nethermind/Chains/foundation.json
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
  src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs
  src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs/MainnetSpecProvider.cs
Labels: new feature, consensus, [Pri] Blocker, BREAKING

#8469 Set ancient barriers for Sepolia post merge
  src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs
  src/Nethermind/Nethermind.Runner/configs/sepolia.json
  src/Nethermind/Nethermind.Runner/configs/sepolia_archive.json
Labels: refactoring, configuration, eip-4444

#8555 Add additional block production logs
  src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs
Labels: logging, new feature
