Repository NethermindEth/nethermind, pull requests merged in 2025-08, with the labels that each got.

#9068 Throw less exceptions during peer connection
  src/Nethermind/Nethermind.Network.Test/PeerManagerTests.cs
  src/Nethermind/Nethermind.Network/PeerManager.cs
  src/Nethermind/Nethermind.Network/Rlpx/IRlpxHost.cs
  src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs
  src/Nethermind/Nethermind.Synchronization.Test/E2ESyncTests.cs
Labels: performance is good

#9074 Add HTML report format
  tools/Kute/Nethermind.Tools.Kute/Assets/report.html
  tools/Kute/Nethermind.Tools.Kute/JsonRpc.cs
  tools/Kute/Nethermind.Tools.Kute/MessageProvider/FileMessageProvider.cs
  tools/Kute/Nethermind.Tools.Kute/Metrics/ConsoleProgressReporter.cs
  tools/Kute/Nethermind.Tools.Kute/Metrics/HtmlMetricsReportFormatter.cs
  tools/Kute/Nethermind.Tools.Kute/Metrics/MetricsReport.cs
  tools/Kute/Nethermind.Tools.Kute/Nethermind.Tools.Kute.csproj
  tools/Kute/Nethermind.Tools.Kute/Program.cs
  tools/Kute/README.md
Labels: kute

#9076 Use proper block params
  src/Nethermind/Nethermind.Blockchain/IBlockTree.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/DebugModuleTests.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugBridge.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugBridge.cs
Labels: rpc

#9082 Optimize unused logging from Diagnostics, Activity and Metrics
  src/Nethermind/Nethermind.Network.Discovery/Discv5/NethermindLoggerFactory.cs
  src/Nethermind/Nethermind.Runner/Ethereum/JsonRpcRunner.cs
  src/Nethermind/Nethermind.Runner/Program.cs
  src/Nethermind/Nethermind.Runner/runtimeconfig.template.json
Labels: performance is good

#9085 Apply RlpxHost options in correct place
  src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs
Labels: bug fix + reliability

#9105 Lower allocation ByteArrayConverter for large hex strings
  src/Nethermind/Nethermind.Core.Test/Json/ByteArrayConverterTests.cs
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Core/JsonConverters/ByteArrayConverter.cs
Labels: performance is good

#9111 Fix crash on after db dispose and concurrent full pruning start
  src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
  src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs
  src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs
Labels: bug fix + reliability

#9116 Report processing log for reorg'd blocks
  src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
Labels: logging

#9118 Add opcode count per block in logs
  src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
  src/Nethermind/Nethermind.Evm/IVirtualMachine.cs
  src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.CodeCopy.cs
  src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.Stack.cs
  src/Nethermind/Nethermind.Evm/Metrics.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Facade/Simulate/SimulateVirtualMachine.cs
Labels: logging, new feature

#9121 Fix for RISC-V
  src/Nethermind/Nethermind.Trie/NibbleExtensions.cs
Labels: bug fix + reliability

#9102 Remove readonly trie store read with custom node storage.
  src/Nethermind/Nethermind.Core.Test/TestRawTrieStore.cs
  src/Nethermind/Nethermind.Trie/Pruning/ITrieStore.cs
  src/Nethermind/Nethermind.Trie/Pruning/ReadOnlyTrieStore.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
Labels: refactoring

#9139 Add OutputCache to metrics endpoint
  src/Nethermind/Nethermind.Monitoring/NethermindKestrelMetricServer.cs
Labels: performance is good

#9144 Correctly Wrap PrepareRequest exeception
  src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
Labels: bug fix + reliability

#9142 Only update metrics if not already updating metrics
  src/Nethermind/Nethermind.Core/Collections/CollectionExtensions.cs
  src/Nethermind/Nethermind.Core/Extensions/MemberInfoExtensions.cs
  src/Nethermind/Nethermind.Core/Threading/ZeroContentionCounter.cs
  src/Nethermind/Nethermind.Init/Steps/StartMonitoring.cs
  src/Nethermind/Nethermind.Monitoring/Metrics/MetricsController.cs
  src/Nethermind/Nethermind.Monitoring/MonitoringService.cs
Labels: performance is good

#9170 Always output logs for processed blocks
  src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
Labels: logging

#9173 Handle Cancellation in SyncPeerPool.Allocate
  src/Nethermind/Nethermind.Synchronization.Test/SyncPeerPoolTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SyncServerTests.cs
  src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs
Labels: bug fix + reliability

#9175 Handle peers shutdown more gracefully
  src/Nethermind/Nethermind.Network.Discovery/DiscoveryApp.cs
  src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
Labels: logging, bug fix + reliability

#9163 Support OP Isthmus at the Genesis block
  src/Nethermind/Nethermind.Api/IApiWithBlockchain.cs
  src/Nethermind/Nethermind.Api/NethermindApi.cs
  src/Nethermind/Nethermind.AuRa.Test/Contract/TestContractBlockchain.cs
  src/Nethermind/Nethermind.Blockchain.Test/GenesisLoaderTests.cs
  src/Nethermind/Nethermind.Blockchain/GenesisLoader.cs
  src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
  src/Nethermind/Nethermind.Core.Test/Builders/BlockBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Modules/PseudoNethermindModule.cs
  src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs
  src/Nethermind/Nethermind.Optimism.Test/OptimismGenesisLoaderTests.cs
  src/Nethermind/Nethermind.Optimism/InitializeBlockchainOptimism.cs
  src/Nethermind/Nethermind.Optimism/OptimismWithdrawals.cs
Labels: optimism

#9064 Incorrect Gas Estimation & Refactoring
  src/Nethermind/Nethermind.Blockchain.Test/TransactionProcessorTests.cs
  src/Nethermind/Nethermind.Blockchain/Tracing/EstimateGasTracer.cs
  src/Nethermind/Nethermind.Blockchain/Tracing/GasEstimator.cs
  src/Nethermind/Nethermind.Evm.Test/Tracing/GasEstimationTests.cs
  src/Nethermind/Nethermind.Facade.Test/BlockchainBridgeTests.cs
Labels: refactoring, bug fix + reliability
