Repository NethermindEth/nethermind, pull requests merged in 2025-06, with the labels that each got.

#8675 Feature/snapsync storage log
  src/Nethermind/Nethermind.Core/Attributes/Metrics.cs
  src/Nethermind/Nethermind.Merge.Plugin/Synchronization/BeaconHeadersSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/SyncDispatcherTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SnapSync/ProgressTrackerTests.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/FastSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/FullSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/Metrics.cs
  src/Nethermind/Nethermind.Synchronization/ParallelSync/ISyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/ParallelSync/NoopSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs
  src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs
  src/Nethermind/Nethermind.Synchronization/SnapSync/SnapSyncFeed.cs
Labels: logging

#8728 Surface acceptTx on sync via config
  src/Nethermind/Nethermind.TxPool/ITxPoolConfig.cs
  src/Nethermind/Nethermind.TxPool/TxPool.cs
  src/Nethermind/Nethermind.TxPool/TxPoolConfig.cs
Labels: new feature

#8719 SpanSource for TrieNode rlp
  src/Nethermind/Nethermind.Benchmark.Runner/Program.cs
  src/Nethermind/Nethermind.Benchmark/Core/SpanSourceBenchmark.cs
  src/Nethermind/Nethermind.Benchmark/Rlp/RlpTrieNodeEncodingBenchmark.cs
  src/Nethermind/Nethermind.Blockchain.Test/Proofs/ReceiptTrieTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/Proofs/TxTrieTests.cs
  src/Nethermind/Nethermind.Core.Test/Buffers/SpanSourceTests.cs
  src/Nethermind/Nethermind.Core/Buffers/ICappedArrayPool.cs
  src/Nethermind/Nethermind.Core/Buffers/ISpanSource.cs
  src/Nethermind/Nethermind.Core/Buffers/ISpanSourcePool.cs
  src/Nethermind/Nethermind.Core/Buffers/SpanSource.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Proof/ProofRpcModuleTests.cs
  src/Nethermind/Nethermind.Serialization.Rlp/AccountDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/ByteArrayExtensions.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpDecoderExtensions.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpFactory.cs
  src/Nethermind/Nethermind.Serialization.Rlp/ValueRlpStream.cs
  src/Nethermind/Nethermind.State.Test/NodeTests.cs
  src/Nethermind/Nethermind.State/Proofs/ProofVerifier.cs
  src/Nethermind/Nethermind.State/Proofs/ReceiptTrie.cs
  src/Nethermind/Nethermind.State/Proofs/TxTrie.cs
  src/Nethermind/Nethermind.State/SnapServer/AccountCollector.cs
  src/Nethermind/Nethermind.State/SnapServer/PathWithStorageCollector.cs
  src/Nethermind/Nethermind.Synchronization.Test/RangeQueryVisitorTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/Trie/RecoveryTests.cs
  src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs
  src/Nethermind/Nethermind.Synchronization/Trie/SnapRangeRecovery.cs
  src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs
  src/Nethermind/Nethermind.Trie.Test/PruningScenariosTests.cs
  src/Nethermind/Nethermind.Trie.Test/TrieNodeTests.cs
  src/Nethermind/Nethermind.Trie/BatchedTrieVisitor.cs
  src/Nethermind/Nethermind.Trie/NodeData.cs
  src/Nethermind/Nethermind.Trie/PatriciaTree.cs
  src/Nethermind/Nethermind.Trie/Pruning/RawScopedTrieStore.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStoreDirtyNodesCache.cs
  src/Nethermind/Nethermind.Trie/RangeQueryVisitor.cs
  src/Nethermind/Nethermind.Trie/TreeDumper.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
  src/Nethermind/Nethermind.Trie/TrieNodeFactory.cs
Labels: performance is good, trie

#8771 Dispose EvmState on warmup
  src/Nethermind/Nethermind.Evm/VirtualMachine.Warmup.cs
Labels: bug fix + reliability

#8781 Recover signer direct from keccak without intermediary array
  src/Nethermind/Nethermind.Core/Crypto/KeccakHash.cs
  src/Nethermind/Nethermind.Crypto/EthereumEcdsaExtensions.cs
  src/Nethermind/Nethermind.Crypto/KeccakRlpStream.cs
  src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/TxDecoders/BlobTxDecoder.cs
Labels: performance is good

#8796 Base prewarming on logical cores
  src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
Labels: performance is good, regression-fix

#8800 PatriciaTree remove unused field
  src/Nethermind/Ethereum.Trie.Test/TrieTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/Proofs/ReceiptTrieTests.cs
  src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsRootCalculator.cs
  src/Nethermind/Nethermind.Core.Test/Builders/BlockBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Builders/BlockTreeBuilder.cs
  src/Nethermind/Nethermind.Core.Test/Builders/TrieBuilder.cs
  src/Nethermind/Nethermind.Era1/EraReader.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Proof/ProofRpcModule.cs
  src/Nethermind/Nethermind.State/Healing/HealingStateTree.cs
  src/Nethermind/Nethermind.State/Healing/HealingStorageTree.cs
  src/Nethermind/Nethermind.State/Proofs/PatriciaTrieT.cs
  src/Nethermind/Nethermind.State/Proofs/ReceiptTrie.cs
  src/Nethermind/Nethermind.State/Proofs/TxTrie.cs
  src/Nethermind/Nethermind.State/Proofs/WithdrawalTrie.cs
  src/Nethermind/Nethermind.State/StateTree.cs
  src/Nethermind/Nethermind.State/StorageTree.cs
  src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
  src/Nethermind/Nethermind.Trie.Test/TrieTests.cs
  src/Nethermind/Nethermind.Trie/PatriciaTree.cs
  tools/Evm/T8n/JsonTypes/T8nExecutionResult.cs
Labels: performance is good

#8655 Perf/allow archive node to use prune cache
  src/Nethermind/Nethermind.Api/NethermindApi.cs
  src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPruningDiskTest.cs
  src/Nethermind/Nethermind.Blockchain.Test/FullPruning/PruningTriggerPruningStrategyTests.cs
  src/Nethermind/Nethermind.Blockchain/FullPruning/PruningTriggerPersistenceStrategy.cs
  src/Nethermind/Nethermind.Blockchain/FullPruning/PruningTriggerPruningStrategy.cs
  src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
  src/Nethermind/Nethermind.Db/IPruningConfig.cs
  src/Nethermind/Nethermind.Db/PruningConfig.cs
  src/Nethermind/Nethermind.Evm.Test/CodeInfoRepositoryTests.cs
  src/Nethermind/Nethermind.Init/Modules/WorldStateModule.cs
  src/Nethermind/Nethermind.Init/PruningTrieStateFactory.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.EthCall.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Proof/ProofRpcModuleTests.cs
  src/Nethermind/Nethermind.Runner.Test/Ethereum/ContextWithMocks.cs
  src/Nethermind/Nethermind.State.Test/PatriciaTreeTests.cs
  src/Nethermind/Nethermind.State.Test/StateReaderTests.cs
  src/Nethermind/Nethermind.State.Test/StatsCollectorTests.cs
  src/Nethermind/Nethermind.State.Test/WorldStateManagerTests.cs
  src/Nethermind/Nethermind.State/IWorldStateManager.cs
  src/Nethermind/Nethermind.State/WorldStateManager.cs
  src/Nethermind/Nethermind.Synchronization.Test/RangeQueryVisitorTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SnapSync/RecreateStateFromAccountRangesTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SnapSync/RecreateStateFromStorageRangesTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SnapSync/SnapProviderTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/TrieScenarios.cs
  src/Nethermind/Nethermind.Trie.Test/OverlayTrieStoreTests.cs
  src/Nethermind/Nethermind.Trie.Test/Pruning/MaxBlockInCachePruneStrategyTests.cs
  src/Nethermind/Nethermind.Trie.Test/Pruning/MinBlockInCachePruneStrategyTests.cs
  src/Nethermind/Nethermind.Trie.Test/Pruning/TestPruningStrategy.cs
  src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs
  src/Nethermind/Nethermind.Trie.Test/PruningScenariosTests.cs
  src/Nethermind/Nethermind.Trie.Test/TrieNodeTests.cs
  src/Nethermind/Nethermind.Trie.Test/TrieTests.cs
  src/Nethermind/Nethermind.Trie/Pruning/CompositePersistenceStrategy.cs
  src/Nethermind/Nethermind.Trie/Pruning/DontDeleteObsoleteNodeStrategy.cs
  src/Nethermind/Nethermind.Trie/Pruning/IPersistenceStrategy.cs
  src/Nethermind/Nethermind.Trie/Pruning/ISnapshotStrategy.cs
  src/Nethermind/Nethermind.Trie/Pruning/MaxBlockInCachePruneStrategy.cs
  src/Nethermind/Nethermind.Trie/Pruning/MemoryLimit.cs
  src/Nethermind/Nethermind.Trie/Pruning/MinBlockInCachePruneStrategy.cs
  src/Nethermind/Nethermind.Trie/Pruning/NoPruning.cs
  src/Nethermind/Nethermind.Trie/Pruning/PersistedMemoryLimit.cs
  src/Nethermind/Nethermind.Trie/Pruning/Prune.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStoreState.cs
Labels: performance is good

#8801 Skip recovery queue when no blocks queued
  src/Nethermind/Nethermind.Blockchain/BlockTree.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
  src/Nethermind/Nethermind.Consensus/Processing/IBlockProcessingQueue.cs
  src/Nethermind/Nethermind.Core/Threading/ThreadExtensions.cs
  src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
  src/Nethermind/Nethermind.Merge.Plugin/TimeoutUtils.cs
Labels: performance is good

#8808 Lighter Memory.Save
  src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
Labels: performance is good

#8821 Single line [DoesNotReturn, StackTraceHidden]
  src/Nethermind/Nethermind.Abi/AbiType.cs
  src/Nethermind/Nethermind.Blockchain/FullPruning/CopyTreeVisitor.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockValidationTransactionsExecutor.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
  src/Nethermind/Nethermind.Core/Buffers/CappedArray.cs
  src/Nethermind/Nethermind.Core/Caching/LinkedListNode.cs
  src/Nethermind/Nethermind.Core/Collections/JournalCollection.cs
  src/Nethermind/Nethermind.Core/Collections/JournalSet.cs
  src/Nethermind/Nethermind.Core/Collections/ThrowHelper.cs
  src/Nethermind/Nethermind.Core/DbSpanMemoryManager.cs
  src/Nethermind/Nethermind.Core/Eip2930/AccessList.cs
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Core/JsonConverters/ByteArrayConverter.cs
  src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
  src/Nethermind/Nethermind.Evm/CodeInfoRepository.cs
  src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
  src/Nethermind/Nethermind.Evm/EvmState.cs
  src/Nethermind/Nethermind.Evm/Instruction.cs
  src/Nethermind/Nethermind.Evm/IntrinsicGasCalculator.cs
  src/Nethermind/Nethermind.Evm/Tracing/NullTxTracer.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.ExternalSigner.Plugin/ClefWallet.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/RpcModuleProvider.cs
  src/Nethermind/Nethermind.Serialization.Json/Base64Converter.cs
  src/Nethermind/Nethermind.Serialization.Json/UInt256Converter.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Eip7702/AuthorizationTupleDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
  src/Nethermind/Nethermind.Serialization.Rlp/ValueRlpStream.cs
  src/Nethermind/Nethermind.Sockets/WebSocketMessageStream.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/FastBlockStatusList.cs
  src/Nethermind/Nethermind.Trie/NibbleExtensions.cs
  src/Nethermind/Nethermind.Trie/NodeData.cs
  src/Nethermind/Nethermind.Trie/PatriciaTree.cs
  src/Nethermind/Nethermind.Trie/Pruning/RawScopedTrieStore.cs
  src/Nethermind/Nethermind.Trie/Pruning/TreePath.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStoreDirtyNodesCache.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
  src/Nethermind/Nethermind.Trie/TrieNode.cs
Labels: refactoring

#8824 Allocate 96 bytes less per tx sender recovery
  src/Nethermind/Nethermind.AuRa.Test/AuRaSealValidatorTests.cs
  src/Nethermind/Nethermind.Benchmark/Core/RecoverSignaturesBenchmark.cs
  src/Nethermind/Nethermind.Clique.Test/CliqueTests.cs
  src/Nethermind/Nethermind.Clique.Test/SnapshotManagerTests.cs
  src/Nethermind/Nethermind.Consensus.AuRa/AuRaSealValidator.cs
  src/Nethermind/Nethermind.Consensus.Clique/CliqueSealer.cs
  src/Nethermind/Nethermind.Consensus.Clique/SnapshotManager.cs
  src/Nethermind/Nethermind.Consensus/ISigner.cs
  src/Nethermind/Nethermind.Consensus/NullSigner.cs
  src/Nethermind/Nethermind.Consensus/Signer.cs
  src/Nethermind/Nethermind.Core.Test/SignerTests.cs
  src/Nethermind/Nethermind.Crypto/BlockHeaderExtensions.cs
  src/Nethermind/Nethermind.Crypto/Ecdsa.cs
  src/Nethermind/Nethermind.Crypto/EthereumEcdsa.cs
  src/Nethermind/Nethermind.Crypto/EthereumEcdsaExtensions.cs
  src/Nethermind/Nethermind.Crypto/IEcdsa.cs
  src/Nethermind/Nethermind.Crypto/IEthereumEcdsa.cs
  src/Nethermind/Nethermind.Crypto/KeccakRlpStream.cs
  src/Nethermind/Nethermind.Crypto/NullEthereumEcdsa.cs
  src/Nethermind/Nethermind.Evm.Test/CodeInfoRepositoryTests.cs
  src/Nethermind/Nethermind.ExternalSigner.Plugin/ClefSigner.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcSimulateTestsBase.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/Simulate/EthSimulateTestsSimplePrecompiles.cs
  src/Nethermind/Nethermind.Network.Discovery/Messages/NodeIdResolver.cs
  src/Nethermind/Nethermind.Network.Discovery/Serializers/DiscoveryMsgSerializerBase.cs
  src/Nethermind/Nethermind.Network.Enr/NodeRecordSigner.cs
  src/Nethermind/Nethermind.Network/Rlpx/Handshake/HandshakeService.cs
  src/Nethermind/Nethermind.Optimism/OptimismEthereumEcdsa.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Eip7702/AuthorizationTupleDecoder.cs
Labels: performance is good

#8825 TransactionSubstate to readonly ref struct
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.Evm/TransactionSubstate.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Taiko/TaikoTransactionProcessor.cs
Labels: performance is good

#8819 Only notify about main BlockchainProcessor shutdown
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
Labels: logging

#8845 Implement Eip7907: Meter Contract Code Size And Increase Limit
  src/Nethermind/Nethermind.Core/CodeSizeConstants.cs
  src/Nethermind/Nethermind.Core/Specs/IReleaseSpec.cs
  src/Nethermind/Nethermind.Core/Specs/ReleaseSpecDecorator.cs
  src/Nethermind/Nethermind.Evm.Test/EvmPooledMemoryTests.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/CodeInfo.cs
  src/Nethermind/Nethermind.Evm/CodeAnalysis/JumpDestinationAnalyzer.cs
  src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
  src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.Call.cs
  src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.CodeCopy.cs
  src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.Create.cs
  src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.Crypto.cs
  src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.Eof.cs
  src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.Storage.cs
  src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.cs
  src/Nethermind/Nethermind.Evm/IntrinsicGasCalculator.cs
  src/Nethermind/Nethermind.Evm/Precompiles/IdentityPrecompile.cs
  src/Nethermind/Nethermind.Evm/Precompiles/Ripemd160Precompile.cs
  src/Nethermind/Nethermind.Evm/Precompiles/Sha256Precompile.cs
  src/Nethermind/Nethermind.Evm/StackAccessTracker.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
  src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs.Test/OverridableReleaseSpec.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs
  src/Nethermind/Nethermind.Specs/Forks/05_SpuriousDragon.cs
  src/Nethermind/Nethermind.Specs/Forks/19_Osaka.cs
  src/Nethermind/Nethermind.Specs/ReleaseSpec.cs
Labels: eip, new feature, osaka

#8853 Split SSTORE to two Opcodes
  src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.Storage.cs
  src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.cs
Labels: refactoring, performance is good

#8820 Don't broadcast txs while processing a block
  src/Nethermind/Nethermind.Blockchain/BlockTree.cs
  src/Nethermind/Nethermind.Blockchain/BlockTreeOverlay.cs
  src/Nethermind/Nethermind.Blockchain/ChainHeadInfoProvider.cs
  src/Nethermind/Nethermind.Blockchain/IBlockTree.cs
  src/Nethermind/Nethermind.Blockchain/ReadOnlyBlockTree.cs
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
  src/Nethermind/Nethermind.TxPool/IChainHeadInfoProvider.cs
  src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs
Labels: performance is good

#8851 Configure Volta Zurich hard fork
  src/Nethermind/Chains/volta.json
Labels: ewf

#8799 Replace Nethermind.Gmp with Nethermind.GmpBindings
  Directory.Packages.props
  src/Nethermind/Nethermind.Evm/Nethermind.Evm.csproj
  src/Nethermind/Nethermind.Evm/Precompiles/ModExpPrecompile.cs
Labels: performance is good

#8870 Add BuilderNet to highlighted log brands
  src/Nethermind/Nethermind.Runner/NLog.config
Labels: logging

#8879 Trim JsonRpc Webhost for lower latency
  src/Nethermind/Nethermind.Core/Transaction.cs
  src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs
  src/Nethermind/Nethermind.JsonRpc/JsonRpcResult.cs
  src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs
  src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/BlockBodiesMessageSerializer.cs
  src/Nethermind/Nethermind.Runner/Ethereum/JsonRpcRunner.cs
  src/Nethermind/Nethermind.Runner/JsonRpc/HostingApplication.cs
  src/Nethermind/Nethermind.Runner/JsonRpc/HttpContextFactory.cs
  src/Nethermind/Nethermind.Runner/JsonRpc/NullDiagnosticListener.cs
  src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
  src/Nethermind/Nethermind.Runner/JsonRpc/WebHost.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpDecoderExtensions.cs
  src/Nethermind/Nethermind.State/Proofs/TxTrie.cs
Labels: performance is good

#8883 Optimize BlockForRpc for eth_getBlockByNumber
  src/Nethermind/Nethermind.Facade/Eth/BlockForRpc.cs
  src/Nethermind/Nethermind.Optimism/Rpc/OptimismEthRpcModule.cs
Labels: performance is good

#8891 fix blob base fee
  src/Nethermind/Nethermind.Evm/CodeAnalysis/IL/EvmToIlEmitter.cs
Labels: evm

#8895 Fix forkids
  src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs
  src/Nethermind/Nethermind.Network/ForkInfo.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
Labels: bug fix + reliability
