Repository NethermindEth/nethermind, pull requests merged in 2025-01, with the labels that each got.

#7990 Reduce per tx execution allocations
  src/Nethermind/Nethermind.Evm.Benchmark/EvmBenchmarks.cs
  src/Nethermind/Nethermind.Evm.Benchmark/MultipleUnsignedOperations.cs
  src/Nethermind/Nethermind.Evm.Benchmark/StaticCallBenchmarks.cs
  src/Nethermind/Nethermind.Evm.Test/EvmStateTests.cs
  src/Nethermind/Nethermind.Evm/EvmState.cs
  src/Nethermind/Nethermind.Evm/StackAccessTracker.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
Labels: performance

#8009 Back Bloom with inline array rather than byte[]
  src/Nethermind/Nethermind.Core.Test/BloomTests.cs
  src/Nethermind/Nethermind.Core/Bloom.cs
  src/Nethermind/Nethermind.Core/Extensions/SpanExtensions.cs
  src/Nethermind/Nethermind.Db/Blooms/BloomStorage.cs
Labels: performance

#8008 Back signature by Vector512 rather than byte[]
  src/Nethermind/Ethereum.Basic.Test/TransactionTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/Consensus/ClefSignerTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/Consensus/NullSignerTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/Consensus/SignerTests.cs
  src/Nethermind/Nethermind.Consensus.Clique/CliqueSealer.cs
  src/Nethermind/Nethermind.Core.Test/Crypto/SignatureTests.cs
  src/Nethermind/Nethermind.Core/Crypto/Signature.cs
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Core/Transaction.cs
  src/Nethermind/Nethermind.Facade/Eth/RpcTransaction/AuthorizationListForRpc.cs
  src/Nethermind/Nethermind.Facade/Eth/RpcTransaction/LegacyTransactionForRpc.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcSimulateTestsBase.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthRpcModule.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Parity/ParityTransaction.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Personal/IPersonalRpcModule.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Personal/PersonalRpcModule.cs
  src/Nethermind/Nethermind.Network.Discovery/Serializers/DiscoveryMsgSerializerBase.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Eip7702/AuthorizationTupleDecoder.cs
Labels: performance

#8001 Move prewarming as early as possible
  src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
Labels: performance

#8052 JsonRpc modules cancellation only on Debugger detached
  src/Nethermind/Nethermind.JsonRpc/JsonRpcConfigExtension.cs
  src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugRpcModule.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Eth/ExecutorBase.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Eth/SimulateTxExecutor.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs
Labels: testing

#8092 Remove array allocation when waiting for visiting tree node children
  src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs
Labels: performance

#8099 Bump version to 1.32.0-unstable
  src/Nethermind/Directory.Build.props
Labels: release
