Repository NethermindEth/nethermind, pull requests merged in 2025-03, with the labels that each got.

#8322 Fix random runner test failure in CI
  src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
Labels: minor

#8365 Build more profitable blocks and improve production logs
  src/Nethermind/Nethermind.Consensus/Processing/BlockExtensions.cs
  src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
  src/Nethermind/Nethermind.Consensus/Producers/BlockProducerBase.cs
  src/Nethermind/Nethermind.Consensus/Producers/IBlockImprovementContextFactory.cs
  src/Nethermind/Nethermind.Core/Address.cs
  src/Nethermind/Nethermind.Core/Block.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.DelayBlockImprovementContextFactory.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.MockBlockImprovementContextFactory.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.PayloadProduction.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.StoringBlockImprovementContextFactory.cs
  src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/BlockImprovementContext.cs
  src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/BlockImprovementContextFactory.cs
  src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/Boost/BoostBlockImprovementContextFactory.cs
  src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/NoBlockImprovementContextFactory.cs
  src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs
  src/Nethermind/Nethermind.Optimism/OptimismPayloadPreparationService.cs
  src/Nethermind/Nethermind.Shutter/ShutterBlockImprovementContext.cs
Labels: performance is good, enhancement

#8366 Small refactor to make ExecuteEvmCall error handling clearer.
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
Labels: consensus

#8360 Change loglevel on invalid websocket state
  src/Nethermind/Nethermind.Sockets/Extensions.cs
Labels: minor

#8403 Fix cpu detection on Windows
  src/Nethermind/Nethermind.Core/Cpu/RuntimeInformation.cs
  src/Nethermind/Nethermind.Core/Cpu/SectionsHelper.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
Labels: bug fix

#8240 Add message with exact error to `AcceptTxResult.Invalid`
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
  src/Nethermind/Nethermind.TxPool/Filters/MalformedTxFilter.cs
Labels: rpc

#8385 Add Hoodi support
  .github/workflows/run-a-single-node-from-branch.yml
  .github/workflows/sync-supported-chains.yml
  scripts/workflow_config/sync_testnets_matrix.json
Labels: devops

#7406 Only write to tree net changes at end of block
  src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
  src/Nethermind/Nethermind.Core/Account.cs
  src/Nethermind/Nethermind.Db/Metrics.cs
  src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
  src/Nethermind/Nethermind.State.Test/StorageProviderTests.cs
  src/Nethermind/Nethermind.State/IWorldState.cs
  src/Nethermind/Nethermind.State/PartialStorageProviderBase.cs
  src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
  src/Nethermind/Nethermind.State/StateProvider.cs
  src/Nethermind/Nethermind.State/StorageTree.cs
  src/Nethermind/Nethermind.State/TransientStorageProvider.cs
  src/Nethermind/Nethermind.State/WorldState.cs
  src/Nethermind/Nethermind.State/WorldStateMetricsDecorator.cs
  src/Nethermind/Nethermind.Trie/Pruning/HashAndTinyPath.cs
  src/Nethermind/Nethermind.Trie/Pruning/TinyTreePath.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
Labels: refactoring, performance is good

#8415 Warm up both beacon root slots
  src/Nethermind/Nethermind.Blockchain.Test/BeaconBlockRootHandlerTests.cs
  src/Nethermind/Nethermind.Blockchain/BeaconBlockRoot/BeaconBlockRootHandler.cs
Labels: performance is good

#8426 Peers ignore self and recent ips
  src/Nethermind/Nethermind.Config/NetworkNode.cs
  src/Nethermind/Nethermind.Network.Discovery.Test/DiscoveryManagerTests.cs
  src/Nethermind/Nethermind.Network.Discovery.Test/E2EDiscoveryTests.cs
  src/Nethermind/Nethermind.Network.Discovery.Test/NodeLifecycleManagerTests.cs
  src/Nethermind/Nethermind.Network.Discovery.Test/NodesLocatorTests.cs
  src/Nethermind/Nethermind.Network.Discovery/CompositeDiscoveryApp.cs
  src/Nethermind/Nethermind.Network.Discovery/DiscoveryApp.cs
  src/Nethermind/Nethermind.Network.Discovery/DiscoveryManager.cs
  src/Nethermind/Nethermind.Network.Discovery/IDiscoveryManager.cs
  src/Nethermind/Nethermind.Network.Discovery/Lifecycle/INodeLifecycleManagerFactory.cs
  src/Nethermind/Nethermind.Network.Discovery/Lifecycle/NodeLifecycleManager.cs
  src/Nethermind/Nethermind.Network.Discovery/Lifecycle/NodeLifecycleManagerFactory.cs
Labels: performance is good

#8438 Lookup TxDecoder once per block
  src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayload.cs
  src/Nethermind/Nethermind.Merge.Plugin/Data/IExecutionPayloadParams.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
  src/Nethermind/Nethermind.Trie/TrackingCappedArrayPool.cs
Labels: performance is good

#8436 Fix taiko DI
  src/Nethermind/Nethermind.Taiko/TaikoPlugin.cs
Labels: refactoring, bug fix + reliability

#8441 Clarify missing messages are Fork Choice
  src/Nethermind/Nethermind.HealthChecks/HealthChecksPlugin.cs
Labels: logging

#8446 Increase hot code in PruneCache
  src/Nethermind/Nethermind.Core/Crypto/Hash256.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStoreDirtyNodesCache.cs
Labels: refactoring, performance is good

#8440 Rlp.Encode skip second array creation for length
  src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
Labels: performance is good
