Repository NethermindEth/nethermind, pull requests merged in 2025-05, with the labels that each got.

#8582 Consider dependency chains in optimal blob packing
  src/Nethermind/Nethermind.AuRa.Test/Transactions/PermissionTxComparerTests.cs
  src/Nethermind/Nethermind.Blockchain.Test/TransactionSelectorTests.cs
  src/Nethermind/Nethermind.Consensus.AuRa/Transactions/TxPriorityTxSource.cs
  src/Nethermind/Nethermind.Consensus/Producers/TxPoolTxSource.cs
  src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs
  src/Nethermind/Nethermind.Core/Extensions/EnumerableExtensions.cs
  src/Nethermind/Nethermind.Core/TransactionExtensions.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/Native/Call/NativeCallTracer.cs
  src/Nethermind/Nethermind.JsonRpc.Test/Modules/FeeHistoryOracleTests.cs
Labels: performance is good, bug fix + reliability

#8577 Fix StateTestTxTracer top-level precompile calls tracing
  src/Nethermind/Nethermind.Test.Runner/StateTestTxTracer.cs
Labels: bug fix + reliability

#8591 Delay resolving to full blob when picking
  src/Nethermind/Nethermind.Consensus/Producers/TxPoolTxSource.cs
Labels: performance is good

#8592 Use faster span enumerator for ArrayPoolList
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
  src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs
  src/Nethermind/Nethermind.Era1/EraReader.cs
  src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/Native/Call/NativeCallTracer.cs
  src/Nethermind/Nethermind.Shutter/ShutterTxLoader.cs
  src/Nethermind/Nethermind.Synchronization.Test/Trie/HealingTreeTests.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
  src/Nethermind/Nethermind.Taiko/Rpc/TaikoEngineRpcModule.cs
Labels: performance is good

#8530 Double check other client limits
  src/Nethermind/Nethermind.Network.Stats/NodeStatsLight.cs
  src/Nethermind/Nethermind.Network.Stats/SyncLimits/BeSuSyncLimits.cs
  src/Nethermind/Nethermind.Network.Stats/SyncLimits/GethSyncLimits.cs
  src/Nethermind/Nethermind.Network.Stats/SyncLimits/NethermindSyncLimits.cs
  src/Nethermind/Nethermind.Network.Stats/SyncLimits/ParitySyncLimits.cs
  src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/FastHeadersSyncTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/ReceiptsSyncFeedTests.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloaderLimits.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs
  src/Nethermind/Nethermind.Synchronization/SyncLimits/BeSuSyncLimits.cs
Labels: refactoring

#8575 Remove Nethermind.Cli
  .github/workflows/build-nethermind-packages.yml
  .github/workflows/nethermind-tests.yml
  .github/workflows/release.yml
  scripts/deployment/build-cli.sh
  src/Nethermind/Directory.Packages.props
  src/Nethermind/Nethermind.Analytics/AnalyticsCliModule.cs
  src/Nethermind/Nethermind.Analytics/Nethermind.Analytics.csproj
  src/Nethermind/Nethermind.Cli.Test/Nethermind.Cli.Test.csproj
  src/Nethermind/Nethermind.Cli.Test/ProofCliModuleTests.cs
  src/Nethermind/Nethermind.Cli.Test/SanitizeCliInputTests.cs
  src/Nethermind/Nethermind.Cli.Test/StatementHistoryManagerTests.cs
  src/Nethermind/Nethermind.Cli/CliEngine.cs
  src/Nethermind/Nethermind.Cli/CliLogger.cs
  src/Nethermind/Nethermind.Cli/CliqueCliModule.cs
  src/Nethermind/Nethermind.Cli/Console/AutoCompletionHandler.cs
  src/Nethermind/Nethermind.Cli/Console/BasicColorScheme.cs
  src/Nethermind/Nethermind.Cli/Console/CliConsole.cs
  src/Nethermind/Nethermind.Cli/Console/ColorScheme.cs
  src/Nethermind/Nethermind.Cli/Console/ColorfulCliConsole.cs
  src/Nethermind/Nethermind.Cli/Console/DraculaColorScheme.cs
  src/Nethermind/Nethermind.Cli/Console/ICliConsole.cs
  src/Nethermind/Nethermind.Cli/Console/StatementHistoryManager.cs
  src/Nethermind/Nethermind.Cli/Console/Terminal.cs
  src/Nethermind/Nethermind.Cli/Converters/BigIntegerTypeConverter.cs
  src/Nethermind/Nethermind.Cli/Converters/FallbackTypeConverter.cs
  src/Nethermind/Nethermind.Cli/ICliEngine.cs
  src/Nethermind/Nethermind.Cli/INodeManager.cs
  src/Nethermind/Nethermind.Cli/Modules/AdminCliModule.cs
  src/Nethermind/Nethermind.Cli/Modules/CliArgumentParserException.cs
  src/Nethermind/Nethermind.Cli/Modules/CliFunctionAttribute.cs
  src/Nethermind/Nethermind.Cli/Modules/CliModuleAttribute.cs
  src/Nethermind/Nethermind.Cli/Modules/CliModuleBase.cs
  src/Nethermind/Nethermind.Cli/Modules/CliModuleLoader.cs
  src/Nethermind/Nethermind.Cli/Modules/CliPropertyAttribute.cs
  src/Nethermind/Nethermind.Cli/Modules/DebugCliModule.cs
  src/Nethermind/Nethermind.Cli/Modules/DiagCliModule.cs
  src/Nethermind/Nethermind.Cli/Modules/EthCliModule.cs
  src/Nethermind/Nethermind.Cli/Modules/NetCliModule.cs
  src/Nethermind/Nethermind.Cli/Modules/NodeCliModule.cs
  src/Nethermind/Nethermind.Cli/Modules/ParityCliModule.cs
  src/Nethermind/Nethermind.Cli/Modules/PersonalCliModule.cs
  src/Nethermind/Nethermind.Cli/Modules/ProofCliModule.cs
  src/Nethermind/Nethermind.Cli/Modules/SystemCliModule.cs
  src/Nethermind/Nethermind.Cli/Modules/TraceCliModule.cs
  src/Nethermind/Nethermind.Cli/Modules/TxPoolCliModule.cs
  src/Nethermind/Nethermind.Cli/Modules/Web3CliModule.cs
  src/Nethermind/Nethermind.Cli/Nethermind.Cli.csproj
  src/Nethermind/Nethermind.Cli/NodeManager.cs
  src/Nethermind/Nethermind.Cli/Program.cs
  src/Nethermind/Nethermind.Cli/Properties/launchSettings.json
  src/Nethermind/Nethermind.slnx
  tools/SendBlobs/BlobSender.cs
  tools/SendBlobs/FundsDistributor.cs
  tools/SendBlobs/HexConvert.cs
  tools/SendBlobs/SendBlobs.csproj
  tools/SendBlobs/SendBlobs.slnx
  tools/SendBlobs/SetupCli.cs
Labels: refactoring

#8599 Trie node encode
  src/Nethermind/Nethermind.Benchmark/Rlp/RlpTrieNodeEncodingBenchmark.cs
  src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
  src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
Labels: performance is good

#8587 Fix/parallel block downloader
  src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncConfig.cs
  src/Nethermind/Nethermind.Blockchain/Synchronization/SyncConfig.cs
  src/Nethermind/Nethermind.Consensus.AuRa/AuRaSealValidator.cs
  src/Nethermind/Nethermind.Consensus/Validators/BlockValidator.cs
  src/Nethermind/Nethermind.Consensus/Validators/HeaderValidator.cs
  src/Nethermind/Nethermind.Core.Test/Builders/BlockTreeBuilder.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/BlockTreeTests.cs
  src/Nethermind/Nethermind.Merge.Plugin/Synchronization/ChainLevelHelper.cs
  src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloader.cs
  src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeSynchronizer.cs
  src/Nethermind/Nethermind.Serialization.Rlp/OwnedBlockBodies.cs
  src/Nethermind/Nethermind.State/Proofs/WithdrawalTrie.cs
  src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.Merge.cs
  src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/ForwardHeaderProviderTests.Merge.cs
  src/Nethermind/Nethermind.Synchronization.Test/ForwardHeaderProviderTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/OldStyleFullSynchronizerTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SyncBatchSizeTests.cs
  src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloadContext.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloadRequest.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/BlocksSyncPeerSelectionStrategy.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/FastSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/FullSyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/IForwardSyncController.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/MultiBlockDownloader.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/PowForwardHeaderProvider.cs
  src/Nethermind/Nethermind.Synchronization/Blocks/SyncBatchSize.cs
  src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs
  src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncFeed.cs
  src/Nethermind/Nethermind.Synchronization/Peers/ISyncPeerPool.cs
  src/Nethermind/Nethermind.Synchronization/SyncFeedComponent.cs
  src/Nethermind/Nethermind.Synchronization/Synchronizer.cs
Labels: performance is good

#8603 HealthChecks: Track CL calls from fcu & np methods
  src/Nethermind/Nethermind.Api/IApiWithNetwork.cs
  src/Nethermind/Nethermind.Api/IEngineRequestsTracker.cs
  src/Nethermind/Nethermind.Api/NethermindApi.cs
  src/Nethermind/Nethermind.HealthChecks.Test/ClHealthTrackerTests.cs
  src/Nethermind/Nethermind.HealthChecks.Test/NodeHealthServiceTests.cs
  src/Nethermind/Nethermind.HealthChecks/ClHealthRequestsTracker.cs
  src/Nethermind/Nethermind.HealthChecks/HealthChecksPlugin.cs
  src/Nethermind/Nethermind.HealthChecks/IClHealthTracker.cs
  src/Nethermind/Nethermind.HealthChecks/NodeHealthService.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/BaseEngineModuleTests.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs
  src/Nethermind/Nethermind.Merge.Plugin.Test/MergePluginTests.cs
  src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Paris.cs
  src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs
  src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
  src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs
  src/Nethermind/Nethermind.Runner/Ethereum/Modules/NethermindRunnerModule.cs
  src/Nethermind/Nethermind.Taiko.Test/TxPoolContentListsTests.cs
  src/Nethermind/Nethermind.Taiko/Rpc/TaikoEngineRpcModule.cs
  src/Nethermind/Nethermind.Taiko/TaikoPlugin.cs
Labels: optimism

#8619 Safely cast Optimism subtypes (2)
  src/Nethermind/Nethermind.Optimism/Rpc/OptimismEthRpcModule.cs
Labels: optimism

#8556 Optimism CL: Enable P2P
  src/Nethermind/Directory.Packages.props
  src/Nethermind/Nethermind.Optimism/CL/BlockId.cs
  src/Nethermind/Nethermind.Optimism/CL/CLConfig.cs
  src/Nethermind/Nethermind.Optimism/CL/Decoding/DecodingPipeline.cs
  src/Nethermind/Nethermind.Optimism/CL/Decoding/IDecodingPipeline.cs
  src/Nethermind/Nethermind.Optimism/CL/Derivation/DerivationPipeline.cs
  src/Nethermind/Nethermind.Optimism/CL/Derivation/ISystemConfigDeriver.cs
  src/Nethermind/Nethermind.Optimism/CL/Derivation/L1BlockInfo.cs
  src/Nethermind/Nethermind.Optimism/CL/Driver.cs
  src/Nethermind/Nethermind.Optimism/CL/ExecutionEngineManager.cs
  src/Nethermind/Nethermind.Optimism/CL/ICLConfig.cs
  src/Nethermind/Nethermind.Optimism/CL/IExecutionEngineManager.cs
  src/Nethermind/Nethermind.Optimism/CL/IL2Api.cs
  src/Nethermind/Nethermind.Optimism/CL/L1Bridge/EthereumBeaconApi.cs
  src/Nethermind/Nethermind.Optimism/CL/L1Bridge/EthereumEthApi.cs
  src/Nethermind/Nethermind.Optimism/CL/L1Bridge/EthereumL1Bridge.cs
  src/Nethermind/Nethermind.Optimism/CL/L1Bridge/IEthApi.cs
  src/Nethermind/Nethermind.Optimism/CL/L1Bridge/IL1Bridge.cs
  src/Nethermind/Nethermind.Optimism/CL/L2Api.cs
  src/Nethermind/Nethermind.Optimism/CL/OptimismCL.cs
  src/Nethermind/Nethermind.Optimism/CL/P2P/OptimismCLP2P.cs
  src/Nethermind/Nethermind.Optimism/CL/P2P/PayloadByNumberProtocol.cs
  src/Nethermind/Nethermind.Optimism/IOptimismConfig.cs
  src/Nethermind/Nethermind.Optimism/OptimismConfig.cs
  src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs
  src/Nethermind/nuget.config
  tools/nuget.config
Labels: optimism

#8642 taiko alethia pacaya fork activation
  src/Nethermind/Chains/taiko-alethia.json
Labels: new feature

#8630 Set default `LegacyTransactionForRpc` gas price to zero
  src/Nethermind/Nethermind.Facade/Eth/RpcTransaction/LegacyTransactionForRpc.cs
Labels: bug fix + reliability

#8646 PatriciaTree ignoreMissingDelete is not used
  src/Nethermind/Nethermind.Trie/PatriciaTree.cs
Labels: refactoring, fun 😃

#8661 Use RocksDB PinnableSlice when available
  src/Nethermind/Nethermind.Core/IKeyValueStore.cs
  src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
  src/Nethermind/Nethermind.Serialization.Rlp/KeyValueStoreRlpExtensions.cs
Labels: performance is good

#8660 Optimize RlpStream.Encode(ulong)
  src/Nethermind/Nethermind.Consensus.Clique/SnapshotDecoder.cs
  src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
Labels: performance is good

#8673 Use static SHA256.HashData
  src/Nethermind/Nethermind.Core/ExecutionRequest/ExecutionRequestExtensions.cs
Labels: performance is good

#8672 Use span when slicing arrays
  src/Nethermind/Nethermind.Optimism/CL/Derivation/DepositTransactionBuilder.cs
  src/Nethermind/Nethermind.Optimism/CL/Derivation/ISystemConfigDeriver.cs
  src/Nethermind/Nethermind.Optimism/CL/P2P/PayloadByNumberProtocol.cs
  src/Nethermind/Nethermind.Trie.Test/TreePathTests.cs
Labels: performance is good

#8674 Mild performance tweaks
  src/Nethermind/Nethermind.Blockchain.Test/BlockchainProcessorTests.cs
  src/Nethermind/Nethermind.Config.Test/ConfigFileTestsBase.cs
  src/Nethermind/Nethermind.Core/Tasks/WaitForPassingTasks.cs
  src/Nethermind/Nethermind.Db.Rocks/Config/PerTableDbConfig.cs
  src/Nethermind/Nethermind.Era1/EraPathUtils.cs
  src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs
  src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
Labels: performance is good

#8679 Fix ClockCache.Set
  src/Nethermind/Nethermind.Core/Account.cs
  src/Nethermind/Nethermind.Core/Caching/ClockCache.cs
Labels: bug fix + reliability

#8663 Implement EIP-7825: Transaction Gas Limit Cap
  src/Nethermind/Nethermind.Blockchain.Test/Validators/TxValidatorTests.cs
  src/Nethermind/Nethermind.Consensus/Messages/TxErrorMessages.cs
  src/Nethermind/Nethermind.Consensus/Validators/TxValidator.cs
  src/Nethermind/Nethermind.Core/Eip7825Constants.cs
  src/Nethermind/Nethermind.Core/Specs/IReleaseSpec.cs
  src/Nethermind/Nethermind.Core/Specs/ReleaseSpecDecorator.cs
  src/Nethermind/Nethermind.Specs.Test/OverridableReleaseSpec.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs
  src/Nethermind/Nethermind.Specs/Forks/19_Osaka.cs
  src/Nethermind/Nethermind.Specs/ReleaseSpec.cs
  src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
Labels: eip, osaka

#8684 Hide OP-CL specific options
  src/Nethermind/Nethermind.Optimism/CL/Rpc/IOptimismOptimismRpcModule.cs
  src/Nethermind/Nethermind.Optimism/IOptimismConfig.cs
Labels: docs, optimism

#8691 Perform stack writes as single 32 vector
  src/Nethermind/Nethermind.Core/Address.cs
  src/Nethermind/Nethermind.Evm/EvmStack.cs
Labels: performance is good

#8489 eip-7883 implementation
  src/Nethermind/Chains/chiado.json
  src/Nethermind/Chains/gnosis.json
  src/Nethermind/Chains/holesky.json
  src/Nethermind/Chains/hoodi.json
  src/Nethermind/Chains/sepolia.json
  src/Nethermind/Ethereum.Blockchain.Pyspec.Test/OsakaBlockChainTests.cs
  src/Nethermind/Ethereum.Blockchain.Pyspec.Test/OsakaEofTests.cs
  src/Nethermind/Ethereum.Blockchain.Pyspec.Test/OsakaStateTests.cs
  src/Nethermind/Nethermind.Core/Specs/IReleaseSpec.cs
  src/Nethermind/Nethermind.Core/Specs/ReleaseSpecDecorator.cs
  src/Nethermind/Nethermind.Evm.Test/Eip7883Tests.cs
  src/Nethermind/Nethermind.Evm/GasCostOf.cs
  src/Nethermind/Nethermind.Evm/Precompiles/ModExpPrecompile.cs
  src/Nethermind/Nethermind.Specs.Test/ChainParametersTests.cs
  src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs.Test/MainnetSpecProviderTests.cs
  src/Nethermind/Nethermind.Specs.Test/OverridableReleaseSpec.cs
  src/Nethermind/Nethermind.Specs.Test/TestSpecHelper.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/AllocationJson.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/BuiltInJson.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecAuRaSealJson.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecEthereumSealJson.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecGenesisJson.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecJson.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecSealJson.cs
  src/Nethermind/Nethermind.Specs/Forks/19_Osaka.cs
  src/Nethermind/Nethermind.Specs/ReleaseSpec.cs
  src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.Blobs.cs
Labels: osaka

#8706 TxParser: Add signature validation, keep errors in 1 line
  tools/TxParser/Program.cs
Labels: bug fix + reliability

#8714 Update known_chain_sizes test
  src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs
Labels: test
