Repository NethermindEth/nethermind, pull requests merged in 2025-07, with the labels that each got.

#8907 Update single node directly rather than creating array
  src/Nethermind/Nethermind.Network.Discovery/DiscoveryManager.cs
Labels: performance is good

#8967 Revise JSON-RPC docs generation
  tools/DocGen/JsonRpcGenerator.cs
Labels: docs

#8976 Cache PropertyInfo lookups for JsonRpc
  src/Nethermind/Nethermind.Core/Collections/TypeAsKey.cs
  src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs
Labels: performance is good

#8982 More hot code in ConnectNodes
  src/Nethermind/Nethermind.Trie/PatriciaTree.cs
Labels: performance is good

#8940 EIP-7594: Constant maxBlobsPerTx
  src/Nethermind/Nethermind.Core/Eip7594Constants.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
  src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/BlobScheduleSettings.cs
  src/Nethermind/Nethermind.Specs/ReleaseSpec.cs
  src/Nethermind/Nethermind.Specs/TestSpecProvider.cs
  src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.Blobs.cs
  src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
Labels: osaka

#8985 Configure EWC Zurich hard fork
  src/Nethermind/Chains/energyweb.json
Labels: ewf

#8994 Fix naming of data cost in ExecutePrecompile
  src/Nethermind/Nethermind.Evm/VirtualMachine.cs
Labels: refactoring

#8992 Replace `eth_pairings` with `mcl`
  Directory.Packages.props
  nuget.config
  src/Nethermind/Nethermind.Blockchain/EthereumCodeInfoRepository.cs
  src/Nethermind/Nethermind.Evm.Precompiles/BN254.cs
  src/Nethermind/Nethermind.Evm.Precompiles/BN254AddPrecompile.cs
  src/Nethermind/Nethermind.Evm.Precompiles/BN254MulPrecompile.cs
  src/Nethermind/Nethermind.Evm.Precompiles/BN254PairingPrecompile.cs
  src/Nethermind/Nethermind.Evm.Precompiles/Extensions.cs
  src/Nethermind/Nethermind.Evm.Precompiles/Nethermind.Evm.Precompiles.csproj
  src/Nethermind/Nethermind.Evm.Precompiles/Snarks/Bn254AddPrecompile.cs
  src/Nethermind/Nethermind.Evm.Precompiles/Snarks/Bn254MulPrecompile.cs
  src/Nethermind/Nethermind.Evm.Precompiles/Snarks/Bn254PairingPrecompile.cs
  src/Nethermind/Nethermind.Evm.Test/BN254AddPrecompileTests.cs
  src/Nethermind/Nethermind.Evm.Test/BN254MulPrecompileTests.cs
  src/Nethermind/Nethermind.Evm.Test/BN254PairingPrecompileTests.cs
  src/Nethermind/Nethermind.Evm.Test/BnAddPrecompileTests.cs
  src/Nethermind/Nethermind.Evm.Test/BnMulPrecompileTests.cs
  src/Nethermind/Nethermind.Evm.Test/BnPairPrecompileTests.cs
  src/Nethermind/Nethermind.Evm.Test/Eip1108Tests.cs
  src/Nethermind/Nethermind.Evm/Nethermind.Evm.csproj
  src/Nethermind/Nethermind.Evm/Precompiles/IPrecompile.cs
  src/Nethermind/Nethermind.Precompiles.Benchmark/BN254AddBenchmark.cs
  src/Nethermind/Nethermind.Precompiles.Benchmark/BN254MulBenchmark.cs
  src/Nethermind/Nethermind.Precompiles.Benchmark/BN254PairingBenchmark.cs
Labels: performance is good

#9008 Optimize ModExp
  src/Nethermind/Benchmarks.slnx
  src/Nethermind/Nethermind.Core/Extensions/ByteArrayExtensions.cs
  src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
  src/Nethermind/Nethermind.Evm.Precompiles/ModExpPrecompile.cs
  src/Nethermind/Nethermind.Evm.Precompiles/ModExpPrecompilePreEip2565.cs
  src/Nethermind/Nethermind.Evm.Test/Eip2565Tests.cs
  src/Nethermind/Nethermind.Evm.Test/Eip7823Tests.cs
  src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.Math2Param.cs
  src/Nethermind/Nethermind.Precompiles.Benchmark/ModExpBenchmark.cs
Labels: performance is good

#9015 Tidy up ecdsa overloads
  src/Nethermind/Nethermind.Consensus.Clique/SnapshotManager.cs
  src/Nethermind/Nethermind.Crypto/EthereumEcdsa.cs
  src/Nethermind/Nethermind.Crypto/IEthereumEcdsa.cs
  src/Nethermind/Nethermind.Crypto/NullEthereumEcdsa.cs
  src/Nethermind/Nethermind.Optimism/OptimismEthereumEcdsa.cs
Labels: refactoring

#9016 Update chain sizes test
  src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs
Labels: test, testing

#8964 Update `ModExp` precompile to the newest version of EIP-7883 (triple pricing)
  src/Nethermind/Nethermind.Evm.Precompiles/ModExpPrecompile.cs
  src/Nethermind/Nethermind.Evm.Test/Eip7883Tests.cs
Labels: osaka

#9025 Remove Linq from Block Processing
  src/Nethermind/Nethermind.Core/BlockInfo.cs
  src/Nethermind/Nethermind.Core/Collections/IHashSetEnumerableCollection.cs
  src/Nethermind/Nethermind.Core/Collections/IToArrayCollection.cs
  src/Nethermind/Nethermind.Core/Collections/JournalCollection.cs
  src/Nethermind/Nethermind.Core/Collections/JournalSet.cs
  src/Nethermind/Nethermind.Evm.Test/TransactionSubstateTests.cs
  src/Nethermind/Nethermind.Evm/TransactionSubstate.cs
  src/Nethermind/Nethermind.JsonRpc/JsonRpcUrl.cs
  src/Nethermind/Nethermind.JsonRpc/Modules/RpcModuleProvider.cs
  src/Nethermind/Nethermind.Serialization.Rlp/ChainLevelDecoder.cs
Labels: performance is good

#9042 Include peer count in both peer reports
  src/Nethermind/Nethermind.Synchronization/Reporting/SyncReport.cs
Labels: logging

#9054 Vectorize Node distance
  src/Nethermind/Nethermind.Network.Discovery.Test/NodeDistanceCalculatorTests.cs
  src/Nethermind/Nethermind.Network.Discovery/DiscoveryConfig.cs
  src/Nethermind/Nethermind.Network.Discovery/IDiscoveryConfig.cs
  src/Nethermind/Nethermind.Network.Discovery/RoutingTable/INodeDistanceCalculator.cs
  src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeDistanceCalculator.cs
  src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeTable.cs
  src/Nethermind/Nethermind.Network.Enr/NodeRecordSigner.cs
Labels: performance is good

#9048 Add support for Prometheus
  Directory.Packages.props
  tools/Kute/Nethermind.Tools.Kute.Test/JsonRpcValidatorTests.cs
  tools/Kute/Nethermind.Tools.Kute.Test/MetricsTests.cs
  tools/Kute/Nethermind.Tools.Kute/Application.cs
  tools/Kute/Nethermind.Tools.Kute/Config.cs
  tools/Kute/Nethermind.Tools.Kute/Extensions/AsyncEnumerableExtensions.cs
  tools/Kute/Nethermind.Tools.Kute/JsonRpc.cs
  tools/Kute/Nethermind.Tools.Kute/JsonRpcValidator/BatchJsonRpcValidator.cs
  tools/Kute/Nethermind.Tools.Kute/JsonRpcValidator/ComposedJsonRpcValidator.cs
  tools/Kute/Nethermind.Tools.Kute/JsonRpcValidator/Eth/NewPayloadJsonRpcValidator.cs
  tools/Kute/Nethermind.Tools.Kute/JsonRpcValidator/Eth/NonErrorJsonRpcValidator.cs
  tools/Kute/Nethermind.Tools.Kute/MessageProvider/JsonRpcMessageProvider.cs
  tools/Kute/Nethermind.Tools.Kute/Metrics/ComposedMetricsReporter.cs
  tools/Kute/Nethermind.Tools.Kute/Metrics/IMetricsReporter.cs
  tools/Kute/Nethermind.Tools.Kute/Metrics/MemoryMetricsReporter.cs
  tools/Kute/Nethermind.Tools.Kute/Metrics/MetricsReport.cs
  tools/Kute/Nethermind.Tools.Kute/Metrics/PrometheusPushGatewayMetricsReporter.cs
  tools/Kute/Nethermind.Tools.Kute/Nethermind.Tools.Kute.csproj
  tools/Kute/Nethermind.Tools.Kute/Program.cs
  tools/Kute/README.md
Labels: kute
