Repository NethermindEth/nethermind, pull requests merged in 2025-02, with the labels that each got.

#8172 Less Prewarmer work per tx (share scope for thread)
  src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
Labels: performance is good

#8173 Optimize TryCalculateFeePerBlobGas
  src/Nethermind/Nethermind.Evm/BlobGasCalculator.cs
Labels: performance is good

#8183 Cleanup/remove last seen map
  src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs
  src/Nethermind/Nethermind.Trie.Test/PruningScenariosTests.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
  src/Nethermind/Nethermind.Trie/Pruning/TrieStoreDirtyNodesCache.cs
Labels: performance is good

#8211 Fix trusted nodes
  src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
Labels: bug

#8179 Shorten boolean command line option notation
  scripts/nethermind.service
  src/Nethermind/Nethermind.Runner/Program.cs
  src/Nethermind/Nethermind.Runner/Properties/launchSettings.json
  tools/DocGen/ConfigGenerator.cs
Labels: cli

#8218 Blockchainprocessor channel use
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
Labels: performance is good

#8248 Skip SLOAD and SSTORE lookups on empty storage
  src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
Labels: performance is good

#8250 Fix RecoveryQueueSize Metric (off by 1)
  src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
Labels: bug fix

#8247 Use rocksdb_get_pinned
  src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
Labels: performance is good

#8251 Capture block stats per log (no block stats bleed)
  src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
Labels: bug fix
